Azure/Azure-AppServices-Diagnostics

data/samples/Diagnostics.Samples/BackupCheckDetector.csx, data/samples/Diagnostics.Samples/Diagnostics.Samples.projitems, src/Diagnostics.DataProviders/DataProviderConfigurations/SupportObserverDataProviderConfiguration.cs, src/Diagnostics.DataProviders/DataProviders/MockSupportObserverDataProvider.cs, src/Diagnostics.DataProviders/DataProviders/SupportObserverDataProvider.cs, src/Diagnostics.DataProviders/MockKustoClient.cs, tests/DataProviderTests/SupportObserverTests.cs
-Reference WAWS Observer API endpoint to get database data.
-Create sample detector. Example, BackupCheckDetector
-Still reference support bay api for RuntimeSiteSlotMap data
=> Add observer passthrough pt2

src/Diagnostics.DataProviders/DataProviders/SupportObserverDataProvider.cs
Currently in prod, when runtimehost tries to get access token from AAD, it throws ArgumentNullException. 
System.AggregateException: One or more errors occurred. (Value cannot be null.) ---> System.ArgumentNullException: Value cannot be null.
at System.Threading.Monitor.Enter(Object obj)
at Diagnostics.DataProviders.SupportObserverDataProvider.<GetAccessToken>d__24.MoveNext() in E:\git\Azure-AppServices-Diagnostics\src\Diagnostics.DataProviders\DataProviders\SupportObserverDataProvider.cs:line 144
Fix: Create a separate object to use for synchronization between threads.
=> Locking on a null value results in ArgumentNullException

src/Diagnostics.RuntimeHost/Services/ResourceService/StampService.cs
Assumption : All the Secondary stamps have just **One letter(a-z)** after the main stamp name.  so it was also remove dr stamps from the list.
Did some research on the existing data  in RoleInstance heartbeat table and so far the assumption looks correct.
=> Fix GetTenantCall in StampService

src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs
This will allow detectors to get properties that are defined at the site root level and not in observer and looks like there are a lot of them which will benefit from this change.
=> Adding support to call the site root path in GeoMasterDataProvider

src/Diagnostics.ModelsAndUtils/Attributes/Definition.cs, src/Diagnostics.ModelsAndUtils/Models/Category.cs, src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/Insight.cs, tests/ModelTests/ResponseExtensionTests.cs
This is just a proof of concept, I will add more predefined categories before I would check in.
Here are the reasons I am doing it this way:
- Enums don't have a way for assigning a string value (with spaces)
- This would give hard coded defaults for people to use so that we are in control of the categories
- If someone wants a category that we have not added, they can use the Custom(name) method, which is really meant to be a stopgap way of not having to wait for a deployment. We would need to push people to add hard coded values later and then updating the detectors. I have some worry about that happening successfully. 
- The UI will just group detectors by category and render them in those groups, no hard coding needed in the UI (applens and support center)
- The exception to this is …
=> Add Category to definition

src/Diagnostics.DataProviders/DataProviderLogDecorator.cs, src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs, src/Diagnostics.DataProviders/Interfaces/IGeoMasterDataProvider.cs
This would allow to query any Geomaster API path over HTTP GET and this should help in all those scenarios where we need data from an endpoint other than 'Microsoft.Web/sites'
=> Adding additional method to GeomasterDataProvider to call any path

src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs
This will allow applens to show KUSTO Query information even in the on-boarding flow
=> Adding dataProvidersMetadata for onboarding flow as well

src/Diagnostics.ModelsAndUtils/Models/Resource/HostingEnvironment.cs, src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs, tests/DataProviderTests/SupportObserverTests.cs
Set the resource name for hosting environment to the stamp name
This may break some ASE detectors but there are few so its easy to edit them.
=> Fix site level for ase

src/Diagnostics.RuntimeHost/Services/GithubClient/GithubClient.cs
Looking over source watcher failures, I noticed that we're logging the github access token. This PR addresses that problem by using the URI object to only log the host and path and not the query strings.
=> Use URI object to remove query path which has token

src/Diagnostics.DataProviders/KustoTokenService.cs, src/Diagnostics.Logger/ETWProvider/DiagnosticsETWProvider.cs, src/Diagnostics.Logger/ETWProvider/ETWMessageTemplates.cs
For whatever reasons, if Kusto token refresh fails, the next token refresh will not happen right now as the service will stop. The fix is to handle exceptions and log. 
There is already alerts now covering this scenario.
=>  LSI Fix : Handle Exceptions in Kusto Token Service

src/Diagnostics.DataProviders/DataProviderLogDecorator.cs, src/Diagnostics.DataProviders/DataProviders/Base/SupportObserverDataProviderBase.cs, src/Diagnostics.DataProviders/DataProviders/ISupportObserverDataProvider.cs, src/Diagnostics.DataProviders/DataProviders/MockSupportObserverDataProvider.cs, src/Diagnostics.DataProviders/DataProviders/SupportObserverDataProvider.cs, src/Diagnostics.RuntimeHost/Controllers/HostingEnvironment/HostingEnvironmentController.cs, src/Diagnostics.RuntimeHost/Controllers/Site/SitesController.cs
Create postbody for site and ASE controller, so we don't need to construct ASE and site specific postbody from client side each time, which will also make all the resource types requests in consistency.
=> Create postbody for site and ase

src/Diagnostics.DataProviders/DataProviderLogDecorator.cs, src/Diagnostics.DataProviders/DataProviders/Base/SupportObserverDataProviderBase.cs, src/Diagnostics.DataProviders/DataProviders/ISupportObserverDataProvider.cs, src/Diagnostics.DataProviders/DataProviders/MockSupportObserverDataProvider.cs, src/Diagnostics.DataProviders/DataProviders/SupportObserverDataProvider.cs
**Allows detector authors to get site data from WawsObserver for a slot.**
-Add slotname to Observer GetSite call
-Since the slotname is an optional parameter it won't break existing detectors and it doesn't require recompilation of all the detectors.
*note:detector authors can technically still get slot data without this change by calling `dp.Observer.GetSite(cxt.Resource.Stamp.Name, $"{cxt.Resource.Name}({cxt.Resource.Slot})")`
=> Add slotname as parameter for observer GetSite call

src/Diagnostics.DataProviders/DataProviderLogDecorator.cs, src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs, src/Diagnostics.DataProviders/DataProviders/KustoDataProvider.cs, src/Diagnostics.DataProviders/Interfaces/IGeoMasterDataProvider.cs, src/Diagnostics.DataProviders/Interfaces/IKustoClient.cs, src/Diagnostics.DataProviders/Interfaces/IKustoDataProvider.cs, src/Diagnostics.DataProviders/KustoClient.cs, src/Diagnostics.DataProviders/MockKustoClient.cs
With this PR, there are two methods that I am adding
1.  **dp.Kusto.GetKustoQuery** - This is for internal detectors that just need KUSTO query information and don't want to execute the query (Basically just give a link for further diagnostics)
```
var k = await dp.Kusto.GetKustoQuery(GetQuery(cxt), cxt.Resource.Stamp.Name);
var kustoDesktop = k.KustoDesktopUrl;
```
2. **Ability to call DAAS API's (GET only)**. This will allow us to get information about site properties in future (like ASP.NET Core versions , Diagnosers supported etc.)
```
var resp = await dp.GeoMaster.InvokeDaasExtension<object>(cxt.Resource.SubscriptionId, cxt.Resource.ResourceGroup, cxt.Resource.Name, cxt.Resource.Slot, "api/diagnosers");
```
=> Kusto and geochanges - Method to call DAAS and detectors to get Kusto Query 

src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs, src/Diagnostics.RuntimeHost/Services/ResourceService/StampService.cs
In V2, I was not caching TenantIds for ASE because they can change if ASE gets recreated.
However, somehow missed that fact while coding up for V3. Hence Updating the TenantId code to only cache the value for Public Stamps (as they will not change)
=> Only Cache TenantIds for Public Stamps

src/Diagnostics.DataProviders/DataProviders/Base/SupportObserverDataProviderBase.cs, tests/DataProviderTests/SupportObserverTests.cs
I removed logic that checked that a path in observer exist. Recently I added new APIs for Mahatab and he couldn't access them through the observer data provider because the path did not exist in the static list of paths written in the SupportObserverDataProviderBase class. Unfortunately I did some over engineering there.
In this pull request, anytime someone sends a request to observer with dp.Observer.GetResource, all this class will do is validate the host is in fact WawsObsever and then it will just send the request via HttpClient. If it doesn't exist, then the detector will get a 404 as expected.
=> Remove the wawsobserver path validation

src/Diagnostics.DataProviders/KustoClient.cs, src/Diagnostics.ModelsAndUtils/Models/DataTableResponseObject.cs
Fixing exceptions that looked like this:
```
System.AggregateException: One or more errors occurred. (Cannot set Column 'S_siteid' to be null. Please use DBNull instead.) ---> System.ArgumentException: Cannot set Column 'S_siteid' to be null. Please use DBNull instead.
```
Adding user agent to kusto client in kestrel process. 
Throwing exception on failed kusto query.
=> Account for null row values and throw exception in kusto client

src/Diagnostics.DataProviders/DataProviders.cs
Using c# properties will break the detectors. Changing this back to use c# fields.
=> Fix for detectors

src/Diagnostics.ModelsAndUtils/ScriptUtilities/Utilities.cs
Fixing a bug in HostNamesFilterQuery function. our queries for wildcard hostnames are incorrect currently...
=> Removing * from hostname in case of wildcard

src/Diagnostics.Logger/ApiMetricsLogger.cs, src/Diagnostics.Logger/Diagnostics.Logger.csproj, src/Diagnostics.Logger/ETWProvider/DiagnosticsETWProvider.cs
Screenshot of headers content logged:
=>  Log x-ms headers received to Kusto

data/templates/Detector_OpenShiftManagedClusters.csx, src/Diagnostics.DataProviders/DataProviderConfigurations/KustoDataProviderConfiguration.cs, src/Diagnostics.DataProviders/DataProviderConfigurations/SupportObserverDataProviderConfiguration.cs, src/Diagnostics.DataProviders/DataProviderConstants.cs, src/Diagnostics.DataProviders/DataProviders/Base/SupportObserverDataProviderBase.cs, src/Diagnostics.RuntimeHost/Services/ResourceService/SiteService.cs, src/Diagnostics.RuntimeHost/Startup.cs, src/Diagnostics.RuntimeHost/appsettings.json
Made some modifications to the project when targeting observer on local host
1. Disable token service for observer as the request to local host will just be HTTP requests
2. Add a feature flag behind local host observer so that we can turn on/off anytime. (This would require diagnostic role config update)
Note this also includes the changes from another pull requests https://github.com/Azure/Azure-AppServices-Diagnostics/pull/151.
=> Local host observer

src/Diagnostics.DataProviders/DataProviders/ChangeAnalysisDataProvider.cs
Change Analysis title was appearing in the data source tab without any information. Removed it.
=> Return null for Change Analysis meta data

src/Diagnostics.DataProviders/Interfaces/IKustoClient.cs, src/Diagnostics.DataProviders/KustoClient.cs
- JSON was failing to deserialize because of additional error object in response
- Check for Kusto error message on response and throw a different exception
- Applens should handle exception to show why the detector was unable to run
=> Check For Kusto "Response Too Large" Error

src/Diagnostics.DataProviders/ChangeAnalysisClient.cs, src/Diagnostics.DataProviders/DataProviderLogDecorator.cs, src/Diagnostics.DataProviders/DataProviders/ChangeAnalysisDataProvider.cs, src/Diagnostics.DataProviders/Interfaces/IChangeAnalysisDataProvider.cs, src/Diagnostics.RuntimeHost/Models/FormModelBinder.cs
These changes will make Change Analysis Data Provider easily consumed by Gist. 
- We can maintain models and logic in the gist and call the Data Provider to forward the request. (Like what ASC Data Provider gist does)
- Logs the exception message if status code is not successful. 
- Increased the form input value to 150 characters so that we can pass detector query params from the UI and it can be consumed in the gist.
=> ChangeAnalysis gist migration

src/Diagnostics.ModelsAndUtils/Models/Rendering.cs
Added new Rendering type for Application Dependency.
The method to add the DataTable to the response object will be maintained in the gist so that in future if we have to add/remove fields sent to the UI, we can do easily.
=> Add new rendering type for application dependencies

src/Diagnostics.ModelsAndUtils/Attributes/Definition.cs
Currently we are using Json SerializeObject and DeserializeObject to make sure we are not overwriting the author info in our InvokerCache:
private Definition RemovePIIFromDefinition(Definition definition, bool isInternal)
{ 
string definitionString = JsonConvert.SerializeObject(definition);
Definition definitionCopy = JsonConvert.DeserializeObject<Definition>(definitionString);
if (!isInternal)
{
definitionCopy.Author = string.Empty;
}
return definitionCopy;
}
However in Definition.cs, AnalysisType is defined as [JsonIgnore], thus the value of  AnalysisTypes we get from AnalysisType property will be null after SerializeObject and DeserializeObject in the above function. Add the set method to set back value from AnalysisTypes to AnalysisType.
=> Analysis is not showing up because deserialize issue

src/Diagnostics.DataProviders/DataProviders/Base/SupportObserverDataProviderBase.cs, src/Diagnostics.RuntimeHost/Startup.cs
- SelfHost Observer cannot pull Georegion connection string from geomaster
- WawsObserver gets the connection string from Service Health Dashboard, a dependency we don't want to add to SelfHost Observer
=> Direct /minienvironment Routes to WawsObserver

src/Diagnostics.DataProviders/DataProviders/Base/SupportObserverDataProviderBase.cs
- Fix routes looking for `/observer` in Observer
- Observer does not have a route for `subscriptions/{}/hostingEnvironments/{}/deployments`, send those to support-bay-api for now
=> Fix Runtime Host Requesting Support Bay API Routes from Observer

src/Diagnostics.RuntimeHost/Services/ResourceService/NationalCloudStampService.cs, src/Diagnostics.RuntimeHost/Services/ResourceService/StampService.cs, src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/LocalFileSystemWatcher.cs, src/Diagnostics.RuntimeHost/Startup.cs
Cloud service domain name suffix is different across clouds, instead of coding for multiple domain names eg., `*.cloudapp.net, *.chinacloudapp.cn` and etc, we should use EventStampName instead which is the SourceMoniker equivalent.
=> Change TenantIdQuery to also query with EventStampName column

src/Diagnostics.DataProviders/KustoHeartBeatService/KustoHeartBeatService.cs
It turns out that the logging for the failover heartbeat was not actually testing the failover cluster instead it was also testing the primary cluster.
This change fixes that bug.
=> fixing a bug in heartbeat logging

src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs
To support error codes and other symbolic queries, relaxing the min char limit from 4 characters to 2 in backend.
=> Relax char min limit in search from 4 down to 2 chars

src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs
This might not be the ideal way to do it, but it seems like the only way for now that we can show CSS internally if application insights is enabled or not.
Going to add this logic to function app insights logging sampling detector.
=> Checking if app insights is set in app settings

src/Diagnostics.RuntimeHost/Controllers/ApiManagement/ApiManagementController.cs, src/Diagnostics.RuntimeHost/Controllers/AppServiceCertificate/AppServiceCertificateController.cs, src/Diagnostics.RuntimeHost/Controllers/AppServiceDomain/AppServiceDomainController.cs, src/Diagnostics.RuntimeHost/Controllers/ArmResource/ArmResourceController.cs, src/Diagnostics.RuntimeHost/Controllers/AzureKubernetesService/AzureKubernetesServiceController.cs, src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs, src/Diagnostics.RuntimeHost/Controllers/HostingEnvironment/HostingEnvironmentController.cs, src/Diagnostics.RuntimeHost/Controllers/InternalAPIController.cs, src/Diagnostics.RuntimeHost/Controllers/LogicApp/LogicAppController.cs, src/Diagnostics.RuntimeHost/Controllers/ObserverController.cs, src/Diagnostics.RuntimeHost/Controllers/Site/SiteControllerBase.cs, src/Diagnostics.RuntimeHost/Controllers/Site/SitesController.cs, src/Diagnostics.RuntimeHost/Diagnostics.RuntimeHost.csproj, src/Diagnostics.RuntimeHost/Startup.cs, src/Diagnostics.RuntimeHost/appsettings.json
- Runtimehost is protected with aad to allow request only from applens
- Healthping controller has not changed so that we can test it to see if the app is up
- In the future sprint, runtimehost will be protected to allow requests from partner app ids as well.
=> Protect runtimehost with AAD

src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs
There could be SAS Uri value for the settings "WEBSITE_RUN_FROM_PACKAGE". Mask the SAS URI before returning it to detector.
=> Remove PII for app settings value

src/Diagnostics.RuntimeHost/Controllers/Site/SitesController.cs, src/Diagnostics.RuntimeHost/Utilities/UriElements.cs
Currently DiagnosticRole has an api for getting site properties which GeoMaster calls. Creating API in runtime host which gets the stack. Other properties can be fetched in GeoMaster.
=> API for getting App Stack

src/Diagnostics.DataProviders/ChangeAnalysisClient.cs, src/Diagnostics.DataProviders/DataProviderContext.cs, src/Diagnostics.DataProviders/DataProviders.cs, src/Diagnostics.DataProviders/DataProviders/ChangeAnalysisDataProvider.cs, src/Diagnostics.Logger/HeaderConstants.cs, src/Diagnostics.RuntimeHost/Middleware/DiagnosticsRequestMiddleware.cs
Change Analysis API requires 4 additional headers : x-ms-client-issuer, x-ms-client-puid, x-ms-client-alt-sec-id, x-ms-client-identity-provider. 
Passing the incoming request headers from DiagnosticRequestMiddleware to ChangeAnalysisClient which adds these headers.
=> Send Additional headers to support CheckAccess ClassAdmin Validation

.gitignore, src/Diagnostics.DataProviders/DataProviders/Base/SupportObserverDataProviderBase.cs, src/Diagnostics.DataProviders/DataProviders/ISupportObserverDataProvider.cs, src/Diagnostics.DataProviders/DataProviders/MockSupportObserverDataProvider.cs, src/Diagnostics.DataProviders/DataProviders/SupportObserverDataProvider.cs, src/Diagnostics.DataProviders/ObserverLogDecorator.cs, src/Diagnostics.RuntimeHost/Controllers/ObserverController.cs
- Use GetAdminSites instead of GetSite for faster stamp name lookup
- Reduce 404 requests to Observer by requiring stamp name for GET RuntimeSiteSlotMap
- Observer does not accept requests to this route without a stamp name
- Check for null or empty stamp name inputs before sending Observer requests to prevent 404 response
- The route `/api/stamps/sites/{sitename}/{resource}` was commonly created, causing 404 responses
=> Reduce Bad Requests To Observer Missing Stamp Name

src/Diagnostics.ModelsAndUtils/ScriptUtilities/Utilities.cs
There are times when the site is browsed with upper / lower case characters in the hostname and we log the case as is in Kusto. The where clause in queries fails for such instances.
=> Changed in with in~ for case insensitive comparison of hostnames.

src/Diagnostics.DataProviders/KustoClient.cs
Changed to using the Static NewGuid method to create an actual Guid instead of an empty Guid object.
=> Fix Guid creation in Kusto client request id generation

src/Diagnostics.DataProviders/ArmClient.cs, src/Diagnostics.DataProviders/ConfigurationFactory.cs, src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs, src/Diagnostics.DataProviders/GeoMasterCertClient.cs, src/Diagnostics.DataProviders/Interfaces/IGeoMasterClient.cs, src/Diagnostics.DataProviders/TokenService/TokenServiceBase.cs, src/Diagnostics.DataProviders/Utility/AsyncMaualResetEvent.cs, src/Diagnostics.RuntimeHost/Startup.cs
This PR refactors GeoMasterDataProvider to remove frequent HttpClient constructions/destructions. It should reduce the number of socket open/close operations and lower the chance of SNAT port exhaustions. This PR also enables to log the full stack traces for first level exceptions.
There was an issue where lots of NullReferenceExceptions happening in the first 20 seconds when the project starts up. This was due to a race condition of the TokenServiceBase class initialization. This PR fixes it by waiting for a property to be populated.
=> Refactor GeoMasterDataProvider

src/Diagnostics.DataProviders/KustoHeartBeatService/KustoHeartBeatService.cs
Updated the Kusto Query to remove follower from the returned data. We add it manually and store it in respective dictionaries.
=> Handle the case where Kusto cluster is already follower in region mappings

src/Diagnostics.DataProviders/DataProviders/SupportObserverDataProvider.cs
- Added clear exception messages if stamp name is not found on adminsites
- Previous logic allowed "StampName" to be present but still returned empty "InternalStampName"; logic now prefers InternalStampName before falling back to StampName
=> Clearer Logic For Pulling Stamp Name From AdminSites

src/Diagnostics.RuntimeHost/Startup.cs
- Set Observer ConnectionLeaseTimeout to 1 minute
- This allows static HttpClient to recover from a swapped endpoint by refreshing the DNS lookup
=> Refresh Observer Connection To Handle Swaps

src/Diagnostics.DataProviders/AscClient.cs, src/Diagnostics.DataProviders/DataProviderConfigurations/ASCDataProviderConfiguration.cs, src/Diagnostics.DataProviders/DataProviders.cs, src/Diagnostics.DataProviders/DataProviders/AscDataProvider.cs, src/Diagnostics.Logger/HeaderConstants.cs, src/Diagnostics.ModelsAndUtils/Models/Resource/ApiManagementService.cs, src/Diagnostics.ModelsAndUtils/Models/Resource/App.cs, src/Diagnostics.ModelsAndUtils/Models/Resource/AppServiceCertificate.cs, src/Diagnostics.ModelsAndUtils/Models/Resource/AppServiceDomain.cs, src/Diagnostics.ModelsAndUtils/Models/Resource/ArmResource.cs, src/Diagnostics.ModelsAndUtils/Models/Resource/AzureKubernetesService.cs, src/Diagnostics.ModelsAndUtils/Models/Resource/HostingEnvironment.cs, src/Diagnostics.ModelsAndUtils/Models/Resource/LogicApp.cs, src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs, src/Diagnostics.RuntimeHost/Controllers/Site/SiteControllerBase.cs, src/Diagnostics.RuntimeHost/appsettings.json
- Based on incoming headers sent from the client (Portal for Diagnose and Solve), create cxt.Resource.SubscriptionLocationPlacementId which can be used in detectors. 
- Block calls to ASC based on subscription location placement id
=> Create cxt.Resource.SubscriptionLocationPlacementId 

src/Diagnostics.DataProviders/AppInsightsLogDecorator.cs, src/Diagnostics.DataProviders/DataProviderConfigurations/AppInsightsDataProviderConfiguration.cs, src/Diagnostics.DataProviders/DataProviders/AppInsightsDataProvider.cs, src/Diagnostics.DataProviders/DataProviders/AppInsightsTag.cs, src/Diagnostics.DataProviders/Interfaces/IAppInsightsDataProvider.cs, src/Diagnostics.ModelsAndUtils/Attributes/ResourceFilter/AppFilter.cs, src/Diagnostics.ModelsAndUtils/Models/AppInsights/AppInsightsTag.cs, src/Diagnostics.RuntimeHost/Controllers/Site/SiteControllerBase.cs, src/Diagnostics.RuntimeHost/appsettings.json
Detector code will do something like this...
```
var isKeyConfigured = await dp.AppInsights.InitializeAppInsightsKey(cxt);
if (isKeyConfigured)
{
res.AddMarkdownView("Yes, key is configured");
var appInsightsData = await dp.AppInsights.ExecuteAppInsightsQuery("requests | where timestamp > ago(1d) | take 5 | project name, url");
res.Dataset.Add(new DiagnosticData()
{
Table = appInsightsData,
RenderingProperties = new TableRendering()
});
}
```
=> Adding InitializeAppInsightsKey to read key from Tags

azure-nationalcloud-pipelines.yml, src/Diagnostics.CompilerHost/Startup.cs, src/Diagnostics.DataProviders/ConfigurationFactory.cs, src/Diagnostics.DataProviders/DataProviderConfigurations/ASCDataProviderConfiguration.cs, src/Diagnostics.DataProviders/DataProviderConfigurations/ChangeAnalysisDataProviderConfiguration.cs, src/Diagnostics.DataProviders/DataProviderConfigurations/SupportObserverDataProviderConfiguration.cs, src/Diagnostics.DataProviders/DataProviders/DiagnosticDataProvider.cs, src/Diagnostics.DataProviders/DataProviders/KustoDataProvider.cs, src/Diagnostics.DataProviders/Diagnostics.DataProviders.csproj, src/Diagnostics.DataProviders/Interfaces/IDiagnosticDataProvider.cs, src/Diagnostics.DataProviders/Interfaces/IKustoDataProvider.cs, src/Diagnostics.DataProviders/KustoLogDecorator.cs, src/Diagnostics.DataProviders/LogDecoratorBase.cs, src/Diagnostics.RuntimeHost/Controllers/ProcessHealthController.cs, src/Diagnostics.RuntimeHost/Diagnostics.RuntimeHost.csproj, src/Diagnostics.RuntimeHost/Extensions/ApplicationLoggingExtensions.cs, src/Diagnostics.RuntimeHost/Middleware/DiagnosticsRequestMiddleware.cs, src/Diagnostics.RuntimeHost/Program.cs, src/Diagnostics.RuntimeHost/Services/HealthCheckService/HealthCheckService.cs, src/Diagnostics.RuntimeHost/Startup.cs, src/Diagnostics.RuntimeHost/appsettings.json
- Remove static KeyVault URL and make it configurable so that it can be configured for different clouds
- By default `AzureServiceTokenProvider` uses public AAD authority, instead make the authority configurable and pass it into the class's constructor
- Log unhanded exceptions to app service application logs and windows event logs
- Create configurable feature flags for each data provider and compilerhost
- Add dependency checker API
- Create overload of ExecuteClusterQuery which takes cluster and database as parameters. This will stop kusto queries from proxying through our clusters
- Remove static text for AAD resource for Observer and create configurable AAD resource.
=> National Cloud Updates

src/Diagnostics.RuntimeHost/Controllers/ApiManagement/ApiManagementController.cs, src/Diagnostics.RuntimeHost/Controllers/AppServiceCertificate/AppServiceCertificateController.cs, src/Diagnostics.RuntimeHost/Controllers/AppServiceDomain/AppServiceDomainController.cs, src/Diagnostics.RuntimeHost/Controllers/ArmResource/ArmResourceController.cs, src/Diagnostics.RuntimeHost/Controllers/AzureKubernetesService/AzureKubernetesServiceController.cs, src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs, src/Diagnostics.RuntimeHost/Controllers/HostingEnvironment/HostingEnvironmentController.cs, src/Diagnostics.RuntimeHost/Controllers/LogicApp/LogicAppController.cs, src/Diagnostics.RuntimeHost/Controllers/Site/SitesController.cs, src/Diagnostics.RuntimeHost/Services/SupportTopicService/SupportTopicService.cs, src/Diagnostics.RuntimeHost/Startup.cs
Modification to the GetInsights method of the controller of every resource type to accept a dynamic post body (where it isn't accepting already) and a supportTopic parameter which is the support topic path.
Pass the post body and supportTopicPath parameter to the base controller i.e. DiagnosticsControllerBase.
This controller takes care of converting the supportTopicPath into a product Id and Support topic Id which is further used in the existing flow of the api.
A support topic service created to carry out the conversion using a support topic path to id mapping obtained from kusto query.
=> ASC bridge with support topic mapping for all partner products

src/Diagnostics.CompilerHost/Startup.cs, src/Diagnostics.RuntimeHost/Startup.cs
We got some logging file locked exceptions because it's a shared resource. Remove this for public azure
=> Remove event log provider for public azure

src/Diagnostics.RuntimeHost/Services/SourceWatcher/Workers/GithubKustoConfigurationWorker.cs, src/Diagnostics.RuntimeHost/Services/SourceWatcher/Workers/GithubScriptWorkerBase.cs, src/Diagnostics.RuntimeHost/Services/SourceWatcher/Workers/GithubWorkerBase.cs
- Include GithubWorker name in the log (GithubGistWorker, GithubDetectorWorker, GithubKustoConfigurationWorker) to distinguish between logs. Right now all these logs coming from different workers have same name "GithubWatcher"
- Skip exception "process cannot access file"
=> Handle exception and fix logging issue

src/Diagnostics.AIProjects/SearchAPI/SearchModule/StorageAccountHelper.py, src/Diagnostics.AIProjects/SearchAPI/SearchModule/TextSearchModule.py
We are trying to avoid any unnecessary writes to the worker file server for refreshing models. This will save trouble when multiple instances are trying to refresh the model and get permission denied error.
=> Model read write improvements

src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs, src/Diagnostics.RuntimeHost/Utilities/Constants.cs
This PR will ensure that detector authors cannot
1. Create a new detector (or Gist) using an ID that already exists in the System
2. Change the ID of an already existing Detector or Gist
=> Avoid detector authors to publish detector with same Id

src/Diagnostics.Logger/ETWProvider/DiagnosticsETWProvider.cs, src/Diagnostics.Logger/ETWProvider/ETWMessageTemplates.cs, src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs, src/Diagnostics.RuntimeHost/Utilities/RuntimeLogger.cs
This PR adds ETW events ranging 5000 to 5003 for runtime event logs.
It also simplifies the runtime exception stack trace shown as a runtime exception insight
=> Enable ETW events for runtime logs

src/Diagnostics.AIProjects/SearchAPI/SearchModule/views.py
It appears that search term is not url decoded before it is sent to search service. This happens only in liberation i.e. Applens. So we will decode it in search service itself to avoid handling in different places.
=> Url decode string before search to resolve search issue in applens

src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/GitHubWatcher.cs, src/Diagnostics.RuntimeHost/Services/SourceWatcher/Workers/GithubDetectorWorker.cs, src/Diagnostics.RuntimeHost/Services/SourceWatcher/Workers/GithubGistWorker.cs, src/Diagnostics.RuntimeHost/Services/SourceWatcher/Workers/GithubKustoConfigurationWorker.cs, src/Diagnostics.RuntimeHost/Services/SourceWatcher/Workers/GithubScriptWorkerBase.cs
Having github client download files in base class can potentially cause race conditions between Gist and Detector SourceWatcher. Moved the github client download operation to GithubWatcher and specific SourceWatchers - Gist, Detector, Kusto will only read from file system and update their caches.
=> Move downloading Github files to GithubWatcher

src/Diagnostics.Scripts/EntityInvoker.cs
When compiling a gist, there is a runtime error showing up, like "Runtime exception has occurred: undefined: undefined undefined." This issue happens because the runtime host tries to invoke the entry point of the compiling .csx file and apparently the gist doesn't have any entry point.
This PR fixes the error by checking if the compiling file is a gist and then it skips to invoke the class.
=> Fix runtime error when compiling a gist

src/Diagnostics.DataProviders/DataProviders/AppInsightsDataProvider.cs, src/Diagnostics.DataProviders/DataProviders/MdmDataProvider.cs, src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs
Since MDM is a field of type `Func<MdmDataSource, IMdmDataProvider>` in DataProviders class, our default logic of casting the field to Interface is not working and we are not getting the dataProvider metadata. 
This change only handles for fields which are of type` Func<Enum, Interface>` so the below logic will not work for `Func<GenericMdmDataProviderConfiguration, IMdmDataProvider>`
=> Checking for Func instead of Interface

src/Diagnostics.DataProviders/MdmClient/MdmClientFactory.cs
I encountered a NullReferenceException while debugging a different issue. This simple PR fixes it.
=> Fix NullRef exception in MdmClientFactory.GetMdmClient()

src/Diagnostics.DataProviders/MdmClient/MdmClientFactory.cs
Cherry-pick: 0672e2705d485365e4bf99b0218a74d3438c57f3
Co-authored-by: Michimune Kohno <mikono@microsoft.com>
=> Fix nullref exceptino in MdmClientFactory.GetMdmClient() (#475)

src/Diagnostics.DataProviders/DataProviders.cs, src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs
With this change,
1. We are creating an object cache in DataProviders for each data provider. Using this cache we can then populate DataProviderMetadata
2. We got rid of all reflection code which was dirty
3. Added an additional call to `GetDataProvidersMetadata(dataProviders);` in `GetDetectorInternal` to update the DataProviderMetadata for all the parameterized DataProviders (like MDM and MDMGeneric)
=> Fixing DataSources issue for MDM

src/Diagnostics.DataProviders/KustoSDKClient.cs
More info on weak consistency 
https://kusto.azurewebsites.net/docs/concepts/queryconsistency.html?q=queryconsistency 
This change will help alleviate some pressure from the admin nodes making the cluster more responsive. The queries however "might" have stale data for up to 5 minutes only from the time of ingestion. Will not add to query latency.
=> Set weak consistency for queries running against Antares Kusto clusters.

src/Diagnostics.DataProviders/KustoHeartBeatService/KustoHeartBeatService.cs
This fixes a bug where `heartbeats `collection does not have any elements. Changed the order inside the if condition to make sure `heartbeats `is loaded
=> check runheartbeatquery flag at end of condition

src/Diagnostics.DataProviders/KustoClient.cs
More info on weak consistency
https://kusto.azurewebsites.net/docs/concepts/queryconsistency.html?q=queryconsistency 
This change will help alleviate some pressure from the admin nodes making the cluster more responsive. The queries however "might" have stale data for up to 5 minutes only from the time of ingestion. Will not add to query latency.
=> Set weak consistency for queries runing against Antares kusto clusters.

src/Diagnostics.Logger/ETWProvider/DiagnosticsETWProvider.cs
As per feedback from Rekha, this PR adds two missing columns to runtime logs.
=> Add DiagEnvironment and DiagWebsiteHostName columns to runtime logs

src/Diagnostics.Logger/ETWProvider/DiagnosticsETWProvider.cs
We believe this PR fixes the two missing columns for runtime logs in Kusto logs.
=> Increment versions of runtime log event attributes

Diagnostics.sln, src/Diagnostics.RuntimeHost/Diagnostics.RuntimeHost.csproj, src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/GitHubWatcher.cs
This change updates the ocktokit client and adds a change to parse and remove tokens from the URL as this is now deprecated.
Will file a bug on github as we shouldn't have to parse the url.
=> Fix GitHub access token in url

src/Diagnostics.DataProviders/DataProviderConfigurations/KustoDataProviderConfiguration.cs, src/Diagnostics.DataProviders/DataProviderConstants.cs, src/Diagnostics.DataProviders/KustoSDKClient.cs, src/Diagnostics.DataProviders/Utility/Helpers.cs, src/Diagnostics.RuntimeHost/appsettings.json
This PR Contains:
- Kusto Retry Logic for specific Exception Types (governed by configuration)
- Using Backup cluster for Last Retry attempt (governed by configuration)
- For instance, if the original query is targeted towards follower cluster, the final retry will happen against main cluster and vice-versa
- for Partners who doesnt have backup clusters, the final retry will be against the same cluster.
- This logic will be automatically applied to `ExecuteQuery` and `ExecuteClusterQuery` but not to `Heartbeat Logic`
- To begin with, we are only retrying in case of :
- Exceptions of type `WeakConsistencyEntityNotFoundException` or `InternalServiceError (520-UnknownError)` . In Last 7 Days, there are 3085 exceptions with these errors and P90 is 8.5 sec.
- Only those kusto requests that …
=> Kusto Retry Logic : Retries on specific exception types

src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs
There was a customer report that one detector showing an incorrect result. We found that the GeoMasterDataProvider.MakeHttpGetRequest() doesn't honor the specified slot name. This PR fixes the issue.
=> Fix GeoMaster.MakeHttpGetRequest ignores slotName

src/Diagnostics.RuntimeHost/Models/Package.cs
I tracked nearly 35 commits in detectors repo where all search terms were getting wiped out entirely due to publishing from local development environments pointing to staging backend or local detector development using VS Code (where addition of search terms is not facilitated).
So we handle this in the ultimate backend where the publishing takes place, we only include metadata in commit if it has some search terms. Null or empty array will be skipped from getting committed.
=> Save search terms from getting wiped out

src/Diagnostics.RuntimeHost/Services/CacheService/DiagEntityTableCacheService.cs
- With this change we can enable ListDetectors call in prod. If detector gets published, the cache service will poll storage every 60secs and keep the cache upto date
=> Changes to enable ListDetectors call completely

src/Diagnostics.ModelsAndUtils/Models/CompilationCache.cs, src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs, src/Diagnostics.RuntimeHost/Services/CacheService/AssemblyCacheService.cs, src/Diagnostics.RuntimeHost/Services/CacheService/Interfaces/IAssemblyCacheService.cs, tests/Diagnostics.Tests.Integration.RuntimeHost/TestData.json
Fix bug where package.json was stored with empty data. Around 20-25 detectors were in this state.
- **Cause:** When detector code was compiled without any changes, empty CompilerResponse object was sent back to AppLens UI and when detector got published, package.json did not have any data
- **Fix:** Added CompilerResponse to the cache so that if detector code was compiled without any changes, backend will send the cached compiler response instead of empty object so package.json gets populated with necessary data
=> Fix bug package.json stored as empty

src/Diagnostics.RuntimeHost/Services/GithubClient/GithubClient.cs, src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/StorageWatcher.cs
Fixing a bug where referencing a gist in detector code wasn't working in Storage SourceWatcher.
When Gist cache is updated, get the script content from Github.
=> Fix gist load using storage watcher

src/Diagnostics.ModelsAndUtils/Models/Resource/ArmResource.cs, src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs, src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/StorageWatcher.cs, src/Diagnostics.RuntimeHost/Services/StorageService/StorageService.cs
- Fixed bug where ListDetectors returned empty list when called from Azure Portal. This was caused due to lowercase in the routing when request came from Azure Portal. Changed the comparison to ignore case and added log statements if there is 0 detectors returned in ListDetectors API call 
- For public endpoints, do not download Gists (.dll and .csx files) because its not required and it will save us time and network calls. This is only needed in euap endpoints because of publishing flow. For other endpoints, download only detector dll 
- Log statement improvements
=> Fixed ListDetectors bug and perf optimization for Storage

src/Diagnostics.RuntimeHost/Services/StorageService/StorageService.cs
This gives the flexibility for us to point some endpoints to secondary storage account. As we look to expand storage feature to all endpoints, this is particularly useful for endpoints that are located faraway from the primary storage account and can face higher latency.
=> Using geo redundancy to achieve high availability

src/Diagnostics.ModelsAndUtils/Attributes/ResourceFilter/ResourceFilterBase.cs, src/Diagnostics.ModelsAndUtils/Models/Resource/ApiManagementService.cs, src/Diagnostics.ModelsAndUtils/Models/Resource/App.cs, src/Diagnostics.ModelsAndUtils/Models/Resource/AppServiceCertificate.cs, src/Diagnostics.ModelsAndUtils/Models/Resource/AppServiceDomain.cs, src/Diagnostics.ModelsAndUtils/Models/Resource/ArmResource.cs, src/Diagnostics.ModelsAndUtils/Models/Resource/AzureKubernetesService.cs, src/Diagnostics.ModelsAndUtils/Models/Resource/HostingEnvironment.cs, src/Diagnostics.ModelsAndUtils/Models/Resource/LogicApp.cs, src/Diagnostics.RuntimeHost/Program.cs, src/Diagnostics.RuntimeHost/Services/CacheService/InvokerCacheService.cs, src/Diagnostics.RuntimeHost/Services/SourceWatcher/SourceWatcherService.cs, src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/GitHubWatcher.cs, src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/LocalFileSystemWatcher.cs, src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/StorageWatcher.cs, src/Diagnostics.Scripts/EntityInvoker.cs, tests/Diagnostics.Tests/Diagnostics.Tests.csproj, tests/Diagnostics.Tests/Helpers/ScriptTestDataHelper.cs, tests/Diagnostics.Tests/ScriptsTests/EntityInvokerTests.cs
Gists can now be created in following  three modes:
| Access Level|Description|  How To Use|
|:----------:|:----------:|:----------:|
| **_Global_**|  Gists are accessible for any resource type |  `[ArmResourceFilter(provider: "*", resourceTypeName: "*")]`  |
| **_RP Level_**|  Gists are accessible for any resource types with same RP |  `[ArmResourceFilter(provider: "Microsoft.FooBar", resourceTypeName: "*")]`  |
| **_Service Level_**|  Gists are only accessible for one particular resource type |  `[ArmResourceFilter(provider: "Microsoft.FooBar", resourceTypeName: "yourServiceName")]`  |
- **Please Note** - Detectors are not sharable as of now. If we need to achieve that, we need to figure out support for different resource type objects to be accepted by one detector. Not in scope of this …
=> Shareable Gists

infrastructure/Scripts/storage-postdeployment.ps1, src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/StorageWatcher.cs, src/Diagnostics.RuntimeHost/Services/StorageService/StorageService.cs, tests/Diagnostics.Tests/AzureStorageTests/AzureStorageTests.cs
- Refresh cache with detectors published in the last 5 mins (Reason behind this: when multiple workers are polling storage, the last cache modified time may be different and out of sync, so on best-effort basis refreshing the cache with detectors modified in last 5 mins)
- Retry 3 times against primary storage account and move to secondary for read path
- table.CreateIfNotExists and container.CreateIfNotExists is causing a lot of noise in the application insight logs. It is seen as dependency failures. So removed those statements and move creation of container and table to script
=> Refresh cache changes and switch to secondary account for read path

src/Diagnostics.RuntimeHost/Extensions/StorageServiceExtensions.cs
`NullableStorageService` was getting injected in public clouds which was failing updates to storage when github watcher is running. Fixing to inject based on cloud domain
=> Fix updates to storage when github is used

src/Diagnostics.DataProviders/DataProviders/SupportObserverDataProvider.cs, src/Diagnostics.ModelsAndUtils/Utilities/AzureSupportCenterInsightUtilities.cs, src/Diagnostics.RuntimeHost/Controllers/Site/SitesController.cs
For mitigating [BUG 1401: Failure to execute detectors when invoked from ASC. GetStampName exception](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1401)
Some requests from ASC to RuntimeHost /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/
providers/Microsoft.Web/sites/{siteName}/**insights** route failed with http 500 because of the site no longer existed.
This PR mitigates this issue by handling the exception raised by `SupportObserverDataProvider.GetStampName()`, logging it to kusto and returning a SiteNotFound insight.
with a kusto link to site deletion records in 30 days, see sample [here](https://dataexplorer.azure.com/clusters/wawswus.kusto.windows.net/databases/wawsprod?query=All%28%27AntaresAdminSubscription …
=> Mitigate GetStampName not found unhandled http 500 exception for RuntimeHost

src/Diagnostics.ModelsAndUtils/Models/GeoMaster/AzureSupportCenterInsight.cs, src/Diagnostics.ModelsAndUtils/Utilities/AzureSupportCenterInsightUtilities.cs
For fixing [BUG 1552: The Azure Data Explorer link in the ASC insight does not work](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1552/)
Figured out that Link Type should be 0 instead of 2. Also added comments to Link.Type field.
=> Fix the kusto link in "SITE NOT FOUND" ASC insight

src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/KeystoneComponent.cs
Insight status can be added to insight like below:
`var myInsight = new KeystoneInsight(InsightStatus.Critical, "Need help with TLS 1.3?",
"TLS 1.3 is not supported on Azure", null, DateTime.UtcNow, DateTime.UtcNow.AddDays(14));`
`res.AddKeystoneComponent(myInsight);`
It can be used in UI to show the user the criticality and importance of a keystone insight.
=> Add Insight status for display

infrastructure/Scripts/keyvault-appsettings.ps1, src/Diagnostics.CompilerHost/Startup.cs, src/Diagnostics.DataProviders/ConfigurationFactory.cs, src/Diagnostics.RuntimeHost/Program.cs, src/Diagnostics.RuntimeHost/appsettings.json
Created separate branch for removing outbound keyvault calls. I will merge this branch to main once the devops pipeline is integrated with the [script ](https://github.com/Azure/Azure-AppServices-Diagnostics/pull/598)and tested. 
- For production and staging, skip outbound calls 
- @hforeste , Can you review this for N-clouds. From your email I learnt that N-clouds is using keyvault app setting reference so it shouldn't be affected.
=> Remove outbound calls to KeyVault for Prod and Staging

src/Diagnostics.DataProviders/DataProviders/MdmDataProvider.cs, src/Diagnostics.DataProviders/Interfaces/IMdmDataProvider.cs, src/Diagnostics.DataProviders/MdmLogDecorator.cs, tests/Diagnostics.Tests/DataProviderTests/DataProviderTests.cs
Add support for custom time grain aggregation while fetching time series in MDM data provider.
=> Support custom time grain aggregation in MDM data provider

src/Diagnostics.RuntimeHost/Startup.cs
- Adding spn: prefix for Client id since AKS team is using ADAL and getting 401 response because ADAL prefixes 'spn:' as audience for token. 
- This doesn't impact current auth as Client id without spn: prefix is also listed
References: [https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/issues/128](url), [https://docs.microsoft.com/en-us/azure/active-directory/develop/single-sign-on-saml-protocol#audience](url)
=> Allow spn prefix for AAD audience

data/templates/Detector_ApiManagementService.csx, data/templates/Detector_AppServiceCertificate.csx, data/templates/Detector_AppServiceDomain.csx, data/templates/Detector_Automation.csx, data/templates/Detector_Batch.csx, data/templates/Detector_BotService.csx, data/templates/Detector_ClassicStorageAccount.csx, data/templates/Detector_ContainerInstance.csx, data/templates/Detector_ContainerRegistry.csx, data/templates/Detector_EventHub.csx, data/templates/Detector_HostingEnvironment.csx, data/templates/Detector_ISE.csx, data/templates/Detector_KubernetesService.csx, data/templates/Detector_LogicApp.csx, data/templates/Detector_MachineLearningServices.csx, data/templates/Detector_NetAppAccounts.csx, data/templates/Detector_OpenShiftManagedClusters.csx, data/templates/Detector_ServiceBus.csx, data/templates/Detector_ServiceFabric.csx, data/templates/Detector_SignalRService.csx, data/templates/Detector_SpringCloudService.csx, data/templates/Detector_StorageAccount.csx, data/templates/Detector_VirtualMachines.csx, data/templates/Detector_WebApp.csx, data/templates/Detector_WebApp_Management.csx
We introduced a new overload of the ExecuteClusterQuery(queryText, clusterName, databaseName, requestId, source) and we want partners to use this overload instead of the older overload of ExecuteClusterQuery(queryText, requestId, source).
The older overload will force the connection to go though wawseus and have Antares kusto act as a proxy increasing the load on our clusters. The new overload will directly connect to the partner's kusto cluster not only speeding up the query by reducing a hop but also reducing load on Antares clusters.
A change in detector template will help ensure any future detectors use the correct overload going forward.
=> Update execute cluster query overload in detector templates for partners

src/Diagnostics.DataProviders/DataProviders/KustoDataProvider.cs
Extract cluster and database name from the query and if it is AKS, connect to the AKS cluster instead of using the Antares cluster as a proxy. Once we ensure this is working, we can apply the logic for all partners wherever we find a cluster and database mentioned in the query.
=> Redirect partner queries using ExecuteClusterQuery directly to the target cluster.

src/Diagnostics.DataProviders/DataProviders/KustoDataProvider.cs
Allow Genevapartner queries that use KustoToMDM plugin to proxy through us. We will reach out to partners on steps to enable their cluster for this plugin and then remove this logic.
=> Allow partner KQL queries to proxy

src/Diagnostics.DataProviders/AppInsightsClient.cs, src/Diagnostics.DataProviders/ChangeAnalysisClient.cs, src/Diagnostics.DataProviders/KustoSDKClient.cs, src/Diagnostics.DataProviders/MdmClient/MdmClient.cs
Fixing potential SNAT issues that could come from DataProviders
- For Kusto, the QueryProviderMapping was static, but the temporary `ICslQueryProvider` object created was not getting disposed after adding to dictionary
- Did a check across other clients and made static HTTP client wherever possible.
After deploying to staging, will monitor and see if it fixes SNAT problems.
=> Fixing potential SNAT issues

src/Diagnostics.RuntimeHost/Services/CompilerHostClient.cs, src/Diagnostics.RuntimeHost/Services/GithubClient/GithubClient.cs, src/Diagnostics.RuntimeHost/Services/HealthCheckService/HealthCheckService.cs, src/Diagnostics.RuntimeHost/Services/SearchService/SearchService.cs
During SNAT investigation, found an issue where outbound connections spike to google.com/generate_204 with the increase in the request to healthping endpoints. This should be avoided. Hence making http client static.
=> Use static httpclient

src/Diagnostics.DataProviders/DataProviders/KustoDataProvider.cs
Extract cluster name if the cluster was specified as FQDN in the query.
=> Fix for ExecuteClusterQuery if it the query contains FQDN cluster name

src/Diagnostics.ModelsAndUtils/Attributes/Definition.cs
Override the TypeId property in Definition Attribute and apply a JsonIgnore attribute to it.
=> Remove type id from response

src/Diagnostics.RuntimeHost/Services/HealthCheckService/HealthCheckService.cs
SNAT issue continued in production site when there was a restart and the load to /healthping route increased. 
After some experimentation and local repro, we found that setting MaxConnectionsPerServer can fix this (thanks @nmallick1!) - https://docs.microsoft.com/en-gb/archive/blogs/timomta/controlling-the-number-of-outgoing-connections-from-httpclient-net-core-or-full-framework
=> Set connection limit for google endpoint

src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs, src/Diagnostics.DataProviders/KustoHeartBeatService/KustoHeartBeatService.cs, src/Diagnostics.DataProviders/MockKustoClient.cs, tests/Diagnostics.Tests/DataProviderTests/DataProviderTests.cs
- Our Heartbeat query count is very high on main kusto clusters and is deemed expensive. It is affecting other operations like wawsalerting etc.
1. Stop continuous pings to main kusto clusters.
2. Whenever failover is required from follower to main, run a heartbeat query on main cluster and if successful, then perform a failover. (Currently, we dont check anything on the main cluster when doing failover :) )
3. Kusto Dashboards will be impacted by this. However not a big thing as we will not see any synthetic SLA for main clusters. We will still continue to see synthetic SLA and failover telemetry for follower clusters.
=> Disable continuous heartbeats to main kusto clusters

src/Diagnostics.AIProjects/TrainingAPI/__app__/TrainingModule/DetectorsFetchHelper.py
Keystone detector is public but it is not supposed to show in Project Shield as it doesn't render any default insights, other than keystone insights. Creating a list for public detectors that need to be ignored in shield.
=> Ignore keystone detector in project shield

src/Diagnostics.RuntimeHost/Services/SupportTopicService/SupportTopicService.cs
Change AzSupport kusto cluster to follower and use the right overload of ExecuteClusterQuery so we directly connect to the follower instead of using our cluster as a proxy.
=> Change AzSupport kusto cluster to follower

src/Diagnostics.RuntimeHost/appsettings.json
In Last 7 days, there has been ~50 API failures due to this exception 'Kusto.DataNode.Exceptions.QueryThrottledException'. The latency of failure is < 200 ms. 
Including this exception in the Retry logic.
=> Retry Kusto Query Throttled Exception 

src/Diagnostics.DataProviders/ChangeAnalysisClient.cs, src/Diagnostics.DataProviders/DataProviderConstants.cs
Service Health Item : User Story 1656: Reduce default timeout for Change Analysis
The Change Analysis detector today only gets surfaced as insight in Web App down analysis. 
If customer clicks on that insight or clicks on 'Application Changes' in the left side menu, we open Application change analysis Blade (owned by Azure tools team). So we dont open the detector view in any scenario.
If this detector fails due to change analysis timeouts, there is no customer experience degradation as its only part of Web app down analysis. The analysis continue to work as is even if change analysis timeouts. However, the API failures impact our SLA (even though there is no customer experience degradation)
Its a two-fold fix. 
A) Catch any exception in the detector. Log the exception in the kusto and …
=> Reduce cancellation token timeout for Change Analysis

src/Diagnostics.DataProviders/DataProviders/KustoDataProvider.cs, src/Diagnostics.DataProviders/Interfaces/IKustoDataProvider.cs, src/Diagnostics.DataProviders/KustoLogDecorator.cs, src/Diagnostics.Scripts/EntityInvoker.cs
Provide a way to execute a query across all of our kusto clusters as All has a heavy toll
throw a compiler error if we detect the use of All in any of the Antares detectors.
=> Add ExecuteOnAllKustoCluster method

src/Diagnostics.ModelsAndUtils/Models/Rendering.cs
Add API for extending data table column configuration to customize width and add filters and detector code as shown below 
Along with UI PR, [Add Table Filters #1055](https://github.com/Azure/Azure-AppServices-Diagnostics-Portal/pull/1055)
```
var columnOptions = new List<TableColumnOption>();
//Config "Computer" column to be invisible with single selection filter
columnOptions.Add(new TableColumnOption(){
Name = "Computer",
SelectionOption = FileterSelectionOption.Single,
Visible = false
});
//Config "Source" column to be multiple choice with customized width
columnOptions.Add(new TableColumnOption(){
Name = "Source",
SelectionOption = FileterSelectionOption.Multiple,
MinWidth= 300,
MaxWidth= 500
});
//Add table into response
res.Dataset.Add(new DiagnosticData(){
Table = table, …
```
=> API for data table filter

src/Diagnostics.ModelsAndUtils/Models/Rendering.cs, src/Diagnostics.ModelsAndUtils/Models/Response.cs
This PR adds a new property named IsVisible to the Rendering class. This allows detectors to return responses which are not displayed by graphic objects but still consumable by CLI, including VS Code extension.
=> Add visible flag

src/Diagnostics.DataProviders/DataProviderConfigurations/SupportObserverDataProviderConfiguration.cs
Fix bug [1685](https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/1685) by adding a `[Required]` attribute to `UnsupportedApis` of in `SupportObserverDataProviderConfiguration.cs `
=> fix bug1685

src/Diagnostics.DataProviders/KeyVaultCertLoader/CertLoaderBase.cs
We were logging the wrong thumbprint info, fixed the log to show what cert we actually loaded and used.
=> Fixing a bug in cert logs

src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs
This PR is to retrieve storage account name from AzureWebJobsStorage settings and return the masked value. This is what AzureWebJobsStorage value looks like:
DefaultEndpointsProtocol=https;AccountName=[name];AccountKey=[key]
=> Show storage account name with masked key from AzureWebJobsStorage setting

src/Diagnostics.ModelsAndUtils/Diagnostics.ModelsAndUtils.csproj
One of our partners reported the following exception while using cxt.Logger -
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.15.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified. File name: 'Microsoft.Extensions.Logging.Abstractions, Version=3.1.15.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' 
Updating the library version to fix this
=> Fix logging exception while using cxt.Logger

src/Diagnostics.RuntimeHost/Services/DiagnosticTranslator/DiagnosticTranslatorService.cs
Now for each rendering type, we allow passing two column lists (one for plain localization and one for html type). For markdown, and insight body value, we localize content as html.
https://docs.microsoft.com/en-us/azure/cognitive-services/translator/reference/v3-0-translate
=> Add option for localize html type for each rendering

src/Diagnostics.RuntimeHost/Utilities/DateTimeHelper.cs
This PR fixes PrepareStartEndTimeUtc() in DateTimeHelper. It unexpectedly handles if endTimeUtc > currentUtcTime.
=> Fix DateTimeHelper logic for endTimeUtc > currentUtcTime

src/Diagnostics.ModelsAndUtils/Models/Rendering.cs
When is not hovering the graph, it will display `--` in metric now, ideally it will show number(by calculating Average/Sum/Max) for each line in graph 
This PR is to allow detector author to specify different ways they want to calculate for metric
=> Enable for different metric types

src/Diagnostics.DataProviders/DataProviderConfigurations/KustoDataProviderConfiguration.cs, src/Diagnostics.DataProviders/DataProviders.cs, src/Diagnostics.DataProviders/DataProviders/Base/SupportObserverDataProviderBase.cs, src/Diagnostics.DataProviders/DataProviders/KustoDataProvider.cs, src/Diagnostics.DataProviders/Interfaces/IKustoClient.cs, src/Diagnostics.DataProviders/KustoSDKClient.cs, src/Diagnostics.DataProviders/MockKustoClient.cs, src/Diagnostics.RuntimeHost/appsettings.json
Enable query shadowing for kusto provider to help testing the new clusters under the same or nearly same traffic as our current follower cluster has so that we can compare the performance in a more scientific way
Minor changes include
- add start and end time in kusto query client Id
- add user agent header in observer data provider http client
=> Enable query shadowing for kusto provider

src/Diagnostics.RuntimeHost/Controllers/ApiManagement/ApiManagementController.cs, src/Diagnostics.RuntimeHost/Controllers/ArmResource/ArmResourceController.cs, src/Diagnostics.RuntimeHost/Controllers/AzureKubernetesService/AzureKubernetesServiceController.cs, src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs, src/Diagnostics.RuntimeHost/Controllers/LogicApp/LogicAppController.cs, src/Diagnostics.RuntimeHost/Controllers/Site/SitesController.cs, src/Diagnostics.RuntimeHost/Controllers/WorkerApp/WorkerAppController.cs, src/Diagnostics.RuntimeHost/Utilities/InsightsAPIHelpers.cs
Insights API in its version 1 had two limitations:
1. It could not accept Detector Forms as input.
2. It was not adding detector query params in the detector deep links it returned
This PR aims to add these two capabilities to the Insights API, as it is used heavily by partners like Azure ML, AKS.
Output link contains all params:
=> Accept Forms and return as query params in Insights API detector links

src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs
Check if the Resource attribute in the current attempt is still applicable to the resource for which AppLens was invoked. If not, fail the compilation and return an appropriate error message.
=> Fail execution of detectors that are not targeted to current resource

src/Diagnostics.DataProviders/KustoSDKClient.cs
Avoid using weak consistency while sending traffic to new leader cluster
=> Use StrongConsistency for new leader

src/Diagnostics.RuntimeHost/runtimeconfig.template.json
Increasing threadpool settings to check if we get rid of detectors taking high latency for runtime host when data providers are not taking high time.
On a side note, this can also be achieved by setting `COMPlus_ThreadPool_ForceMinWorkerThreads=0x50` environment variable. Not sure which one is easier to maintain for us. I felt its the project code hence I found a configuration way to do this.
=> Increase Thread Pool MinThreads to 90

src/Diagnostics.CompilerHost/Startup.cs, src/Diagnostics.DataProviders/TokenService/LogAnalyticsTokenServiceBase.cs, src/Diagnostics.ModelsAndUtils/Models/Storage/DeploymentParameters.cs, src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs, src/Diagnostics.RuntimeHost/Extensions/StorageServiceExtensions.cs, src/Diagnostics.RuntimeHost/SerializationConvertors/AsRuntimeTypeConverter.cs, src/Diagnostics.RuntimeHost/Startup.cs
This PR fixes the empty response from runtimehost when compiling a detector.
This PR also changes the following things:
- Add ConfigureAwait(false) for some async calls
- Disable Application Insights for local development mode
- Fix unhandled exception when launching runtime host if CloudDomain is set to UnitTest
=> Fix broken compile response

src/Diagnostics.RuntimeHost/SerializationConvertors/AsRuntimeTypeConverter.cs, src/Diagnostics.RuntimeHost/Startup.cs
This PR fixes an issue with System.Text.Json where no runtime errors are correctly serialized.
=> Fix regression no runtime error is correctly rendered

src/Diagnostics.ModelsAndUtils/Models/CompilerResponse.cs, src/Diagnostics.ModelsAndUtils/Models/QueryResponse.cs, src/Diagnostics.RuntimeHost/SerializationConvertors/AsRuntimeTypeConverter.cs, src/Diagnostics.RuntimeHost/Startup.cs
This PR should finally fix recent several rendering issues, including DynamicInsightRendering. It also fixes the infinite "track" events after compilation.
This PR reverts my recent change which uses the IncludeFields flag for JSON serialization. It also removes the converter for QueryResponse<> because it conflicts with rendering Rendering objects within.
This PR also renames AsNonGenericTypeConverter to AsPrintableTypeConverter because it makes more sense. It is used to serialize Exception and all of its derived classes.
=> Fix DynamicInsightRendering rendering

src/Diagnostics.DataProviders/DataProviders/KustoDataProvider.cs
Detectors using dp.Kusto.GetKustoQuery (e.g. DWASQuery and many more) are broken in staging because we changed the fields of the KustoQuery class and those calls are failing with FieldNotFound exceptions. 
This PR will fix that issue.
=> System.Text.Json issue - Fix for GetKustoQuery method used by existing detectors

src/Diagnostics.RuntimeHost/SerializationConvertors/AsRuntimeTypeConverter.cs, src/Diagnostics.RuntimeHost/Startup.cs
This PR fixes an issue where runtime exception isn't correctly shown in the runtime output text when compiling a detector.
=> Fix runtime exception incorrectly shown in the runtime logs

src/Diagnostics.DataProviders/DataProviderConfigurations/KustoDataProviderConfiguration.cs, src/Diagnostics.DataProviders/DataProviders/KustoDataProvider.cs, src/Diagnostics.DataProviders/Interfaces/IKustoDataProvider.cs, src/Diagnostics.DataProviders/KustoLogDecorator.cs, src/Diagnostics.DataProviders/KustoSDKClient.cs, src/Diagnostics.RuntimeHost/appsettings.json
If test cluster exists, KustSDKClient will use test leader cluster first and falls back to normal routine on any failure
Besides, add a `GetAggHiPerfClusterNameByStampAsync` function to KustoDataProvider
=> KustSDKClient uses test leader cluster

src/Diagnostics.DataProviders/KustoSDKClient.cs
Use strong consistency for queries fired against aggregate cluster
=> Use strong consistency for queries fired against aggregate cluster

src/Diagnostics.DataProviders/DataProviders/KustoDataProvider.cs, src/Diagnostics.DataProviders/Interfaces/IKustoDataProvider.cs, src/Diagnostics.DataProviders/KustoLogDecorator.cs
Kusto execute cluster does not honor custom database name when showing queries in data source.
Added additional method to get Kusto query based on a custom cluster and database name.
=> Kusto execute cluster does not honor custom database name when showing queries in data source

src/Diagnostics.Scripts/EntityInvoker.cs
Block All Kusto function for static web apps detector development experience.
Detector authors are using the All function and those queries are timing out. Cross cluster queries are slow and end up increasing the concurrency of cluster and may lead to throttling.
=> Block All Kusto function for static web apps

src/Diagnostics.DataProviders/DataProviderConfigurations/KustoDataProviderConfiguration.cs, src/Diagnostics.DataProviders/KustoSDKClient.cs, src/Diagnostics.RuntimeHost/appsettings.json
will update the `KustoClusterNameGroupings` configuration in Diagnostics KV to replace `wawscusfollower` by `wawscusdiagleader.centralus`
=> stop testing wawscusdiagleader.centralus

src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/Form.cs
The basic reason why these issues are coming is because System.Text.Json does not by default serialize Fields. It only serializes Properties. Due to which, anything that is marked as field may not get serialized properly. This is documented here:
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-how-to?pivots=dotnet-core-3-1#include-fields
The fix is to upgrade to .NET Core 5+ and use the `[JsonInclude]` attribute but if an app needs a fix fix it in 3.1, they need to write a JsonConverter. I tried writing like below. This is fixing this issue but now the Insights stop coming so maybe some more checks need to be added.
```
public class FieldConverter : JsonConverter<object>
{
public override object Read(ref Utf8JsonReader reader, Type typeToConvert, …
```
=> System.Text.Json fix for radio buttons not rendered properly

src/Diagnostics.DataProviders/DataProviders/KustoDataProvider.cs, src/Diagnostics.DataProviders/Interfaces/IKustoDataProvider.cs, src/Diagnostics.DataProviders/KustoLogDecorator.cs
Allow a query to be executed on a few app service clusters instead of all. This eliminated the need to perform a cross cluster union and enables scenarios where a query should be executed in few regions. This is being created to enable certain scenarios for static webapps.
=> Allow a query to be executed on a few app service clusters

src/Diagnostics.DataProviders/DataProviderConfigurations/AntaresMdmDataProviderConfiguration.cs, src/Diagnostics.DataProviders/DataProviderConfigurations/ContainerAppsMdmDataProviderConfiguration.cs, src/Diagnostics.DataProviders/DataProviderConfigurations/GenericMdmDataProviderConfiguration.cs, src/Diagnostics.DataProviders/DataProviderConfigurations/IMdmDataProviderConfiguration.cs
This is to fix a regression caused by change abfda9b4545a4261a98a2ed5b4dc9b5dc792b10b which removed the CertificateName property from IMdmDataProviderConfiguration.
=> Revert IMdmDataProviderConfiguration change which removed CertificateName

src/Diagnostics.DataProviders/DataProviderConfigurations/KustoDataProviderConfiguration.cs, src/Diagnostics.DataProviders/KustoHeartBeatService/KustoHeartBeatService.cs, src/Diagnostics.DataProviders/KustoSDKClient.cs, src/Diagnostics.RuntimeHost/appsettings.json
- change GetClusterNameFromStamp function to use new diagleader when updating a missing region:cluster mapping
- add shadowing for wawswus and wawsneu
- turn on agg cluster for all regions
- not use weak consistency for all diagleader clusters
=> updates for kusto diag leaders

src/Diagnostics.RuntimeHost/Controllers/DeploymentController.cs, src/Diagnostics.RuntimeHost/Services/DevOpsClient/DevOpsClient.cs
- This improvement speeds up time to onboard resources and does not require process restart
- Fetches from storage on-demand instead of polling which reduces the no of API requests to storage 
- Previously to onboard resources would require config change followed by site restart. With this change, only config change is needed, and the web app will fetch from storage the next time API is queried for the newly onboarded resource. 
- Nothing changes from UI. It works same way for existing onboarded resources.
=> Fetch config from storage if not in cache

src/Diagnostics.ModelsAndUtils/Utilities/AzureSupportCenterInsightUtilities.cs, src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs
Handle Null checks and create appropriate log messages in GetInsights API when it gets called for a ST that does not have a detector mapped to it.
=> Handle Null checks and create appropriate log messages.

src/Diagnostics.RuntimeHost/Controllers/ApiManagement/ApiManagementController.cs, src/Diagnostics.RuntimeHost/Controllers/AppServiceCertificate/AppServiceCertificateController.cs, src/Diagnostics.RuntimeHost/Controllers/AppServiceDomain/AppServiceDomainController.cs, src/Diagnostics.RuntimeHost/Controllers/ArmResource/ArmResourceController.cs, src/Diagnostics.RuntimeHost/Controllers/AzureKubernetesService/AzureKubernetesServiceController.cs, src/Diagnostics.RuntimeHost/Controllers/ContainerApp/ContainerAppController.cs, src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs, src/Diagnostics.RuntimeHost/Controllers/HostingEnvironment/HostingEnvironmentController.cs, src/Diagnostics.RuntimeHost/Controllers/LogicApp/LogicAppController.cs, src/Diagnostics.RuntimeHost/Controllers/Site/SitesController.cs
There are times when an engineer would modify the product in ASC but the ST for that case still points to the old product, for example, the resource selected is an Azure Web App however the case was originally created against AppServiceCertificate. In such cases, we will fail to find an applicable detector since none would match the ST and we were throwing NRE.
=> Nmallick1/handle incorrect st for resource type 

src/Diagnostics.RuntimeHost/Startup.cs
Check if Provider is enabled before loading certs for it. This will help selectively disable providers across NClouds.
=> Check if Provider is enabled before loading certs for it.

src/Diagnostics.RuntimeHost/Controllers/DeploymentController.cs
Fixed a bug where if multiple detectors using same gist reference were deployed in the same API, the key exists exception is thrown.
=> Use TryAdd to avoid Key exists exception
