Azure/Azure-AppServices-Diagnostics

src/Diagnostics.CompilerHost/Diagnostics.CompilerHost.csproj
src/Diagnostics.ModelsAndUtils/ScriptUtilities/ScriptHelper.cs
src/Diagnostics.RuntimeHost/Diagnostics.RuntimeHost.csproj
src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/GitHubWatcher.cs
src/Diagnostics.RuntimeHost/appsettings.json
src/Diagnostics.Scripts/Diagnostics.Scripts.csproj
tests/Diagnostics.Tests.csproj

- Include commonly used dlls
- Handle exceptions in assembly load
- Watcher fixes for case senstitive matches

Bug Fixes 

---

src/Diagnostics.ModelsAndUtils/Models/Rendering.cs
src/Diagnostics.RuntimeHost/Controllers/SitesController.cs

List API should return array of detector responses

Renaming member and updating list API

---

src/Diagnostics.ModelsAndUtils/Models/Rendering.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/DataSummary.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/Email.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/Insight.cs
tests/ModelTests/ResponseExtensionTests.cs

Added following Extension methods:
response.AddInsight(...) 
response.AddEmail(...)
response.AddDataSummary(...)
- Basic test coverage for these methods.

Response Extension Methods

---

src/Diagnostics.RuntimeHost/Controllers/SitesController.cs

There were a few problems with my last change that I am correcting. 
I only deployed to msftintdm3 and patched those instances with this fix to get it working.

Fixing issues in SitesController

---

src/Diagnostics.ModelsAndUtils/Models/Rendering.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/DynamicInsight.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/Insight.cs
src/Diagnostics.Scripts/Models/EntityMethodSignature.cs
tests/ModelTests/ResponseExtensionTests.cs

Add Dynamic Insights

---

src/Diagnostics.DataProviders/DataProviders/Base/SupportObserverDataProviderBase.cs
src/Diagnostics.DataProviders/DataProviders/ISupportObserverDataProvider.cs
src/Diagnostics.DataProviders/DataProviders/MockSupportObserverDataProvider.cs
src/Diagnostics.DataProviders/DataProviders/SupportObserverDataProvider.cs
src/Diagnostics.DataProviders/KustoClient.cs

-Unblock migration detector creation by adding support observer APIs
-Fix for issue https://github.com/ShekharGupta1988/AppLensV2/issues/1135

Add SupportObserver APIs for Migration and Fix Bug in KustoClient

---

data/documentation/docfx.json
src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs
src/Diagnostics.ModelsAndUtils/Models/GeoMaster/GeoMasterResponse.cs

1.  Added documentation for all the methods
2.  Added logic to filter out sensitive app settings
3.  Added a generic method that can be called for HTTP GET requests for ARM\GeoMaster

Adding documentation to Geomasterdata provider and other updates

---

src/Diagnostics.DataProviders/ConfigurationFactory.cs
src/Diagnostics.DataProviders/DataProviders/DiagnosticDataProvider.cs
src/Diagnostics.DataProviders/DataProviders/KustoDataProvider.cs
src/Diagnostics.DataProviders/Interfaces/IKustoClient.cs
src/Diagnostics.DataProviders/KustoClient.cs
src/Diagnostics.DataProviders/MockKustoClient.cs
src/Diagnostics.ModelsAndUtils/Models/DataProviderMetadata.cs
src/Diagnostics.ModelsAndUtils/Models/Response.cs
src/Diagnostics.RuntimeHost/Controllers/ControllerBase.cs
tests/DataProviderTests/DataProviderTests.cs

Submitting an initial PR to get some feedback on whether I am on right track or not.

Adding KUSTO queries to DetectorResponse

---

src/Diagnostics.Logger/ETWProvider/DiagnosticsETWProvider.cs
src/Diagnostics.Logger/ETWProvider/ETWMessageTemplates.cs
src/Diagnostics.ModelsAndUtils/Models/GeoMaster/AzureSupportCenterInsight.cs
src/Diagnostics.ModelsAndUtils/Models/Response.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/Insight.cs
src/Diagnostics.RuntimeHost/Controllers/ControllerBase.cs
src/Diagnostics.RuntimeHost/Controllers/HostingEnvironment/HostingEnvironmentController.cs
src/Diagnostics.RuntimeHost/Controllers/Site/SitesController.cs
src/Diagnostics.RuntimeHost/Utilities/AzureSupportCenterInsightUtilities.cs
src/Diagnostics.RuntimeHost/Utilities/UriElements.cs

This is the first draft of the insights change, I want to get eyes on it ASAP.

Insights Take 1

---

src/Diagnostics.DataProviders/AppInsightsClient.cs
src/Diagnostics.DataProviders/DataProviderConfigurations/AppInsightsDataProviderConfiguration.cs
src/Diagnostics.DataProviders/DataProviderLogDecorator.cs
src/Diagnostics.DataProviders/DataProviders.cs
src/Diagnostics.DataProviders/DataProviders/AppInsightsDataProvider.cs
src/Diagnostics.DataProviders/DataSourcesConfiguration.cs
src/Diagnostics.DataProviders/Interfaces/IAppInsightsClient.cs
src/Diagnostics.DataProviders/Interfaces/IAppInsightsDataProvider.cs
src/Diagnostics.ModelsAndUtils/Models/DataTableResponseObject.cs
src/Diagnostics.RuntimeHost/Services/InvokerCacheService.cs
src/Diagnostics.RuntimeHost/appsettings.json

Add ApplicationInsights data provider for diagnostic role.

Add ApplicationInsights data provider

---

src/Diagnostics.Logger/ETWProvider/DiagnosticsETWProvider.cs
src/Diagnostics.ModelsAndUtils/Models/Response.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/DetectorStatus.cs

Updating event id in order to make the data flow properly

Use only one Status enum and update event Id

---

src/Diagnostics.RuntimeHost/Controllers/ApiManagement/ApiManagementController.cs
src/Diagnostics.RuntimeHost/Controllers/AppServiceCertificate/AppServiceCertificateController.cs
src/Diagnostics.RuntimeHost/Controllers/AppServiceDomain/AppServiceDomainController.cs
src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs
src/Diagnostics.RuntimeHost/Controllers/HostingEnvironment/HostingEnvironmentController.cs
src/Diagnostics.RuntimeHost/Controllers/LogicApp/LogicAppController.cs
src/Diagnostics.RuntimeHost/Controllers/Site/SitesController.cs

Add support topic list of related detector to system invoker context

Add support topic list to system invoker context

---

src/Diagnostics.ModelsAndUtils/Models/Rendering.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/Markdown.cs

Back end change so that the detector owner can decide if they want to show the email buttons or not in applens

Make Email Buttons Disabled By Default

---

src/Diagnostics.RuntimeHost/Models/SourceWatcherExceptions.cs
src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/GitHubWatcher.cs
src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/LocalFileSystemWatcher.cs
src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/SourceWatcherBase.cs

Show source watcher type of exceptions in diagnostic dashboard.

Modify source watcher logging

---

src/Diagnostics.RuntimeHost/Controllers/Site/SitesController.cs

Assign new postbody also for non-empty default postbody constructor

Assign new postbody also for non-empty default postbody constructor

---

src/Diagnostics.DataProviders/DataProviderContext.cs
src/Diagnostics.DataProviders/DataProviderLogDecorator.cs
src/Diagnostics.DataProviders/DataProviders.cs
src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs
src/Diagnostics.RuntimeHost/Controllers/HostingEnvironment/HostingEnvironmentController.cs
src/Diagnostics.RuntimeHost/Controllers/Site/SiteControllerBase.cs
src/Diagnostics.RuntimeHost/Controllers/Site/SitesController.cs
src/Diagnostics.RuntimeHost/Middleware/DiagnosticsRequestMiddleware.cs
src/Diagnostics.RuntimeHost/Models/RuntimeContext.cs
src/Diagnostics.RuntimeHost/Services/ResourceService/SiteService.cs
src/Diagnostics.RuntimeHost/Services/ResourceService/StampService.cs
src/Diagnostics.RuntimeHost/Utilities/Constants.cs
tests/DataProviderTests/DataProviderTests.cs
tests/DataProviderTests/SupportObserverTests.cs

- Log request id in data provider logging. Events 3001-3003
- Add 60 second timeout to request

Improve logging

---

src/Diagnostics.DataProviders/DataProviderConfigurations/KustoDataProviderConfiguration.cs
src/Diagnostics.DataProviders/DataProviderConstants.cs
src/Diagnostics.DataProviders/KustoTokenService.cs
src/Diagnostics.RuntimeHost/appsettings.json

- Makekusto AAD authentication parameters configurable for different tenants and resources such as China Cloud and Public Azure.
- Remove static constants for authentication
- Add default values to appsettings

Configuration AAD Parameters

---

src/Diagnostics.ModelsAndUtils/Attributes/ResourceFilter/AzureKubernetesServiceFilter.cs
src/Diagnostics.ModelsAndUtils/Attributes/ResourceFilter/Enumerations.cs
src/Diagnostics.ModelsAndUtils/Models/Rendering.cs
src/Diagnostics.ModelsAndUtils/Models/Resource/AzureKubernetesService.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/Guage.cs
src/Diagnostics.RuntimeHost/Controllers/AzureKubernetesService/AzureKubernetesServiceController.cs
src/Diagnostics.RuntimeHost/Utilities/UriElements.cs

Adding support for AKS resource type and Guage rendering

AKS and Guage Rendering

---

src/Diagnostics.DataProviders/DataProviderConfigurations/MdmDataProviderConfiguration.cs
src/Diagnostics.DataProviders/DataProviders.cs
src/Diagnostics.RuntimeHost/appsettings.json
tests/DataProviderTests/DataProviderTests.cs

- Disable MDM data provider for now
- Fix Registry key value names

Fix/Disable MDM

---

data/templates/Gist_ApiManagementService.csx
data/templates/Gist_AppServiceCertificate.csx
data/templates/Gist_AppServiceDomain.csx
data/templates/Gist_KubernetesService.csx
data/templates/Gist_LogicApp.csx

Gist templates for: 
- ApiManagementService 
- AppServiceCertificate 
- AppServiceDomain 
- KubernetesService 
- LogicApp

Add gist templates

---

src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs

Changed headers to start with diag-

Add headers to start with 'diag-'

---

src/Diagnostics.ModelsAndUtils/Models/Rendering.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/Markdown.cs

Add the flag to remove markdown border

Add the flag to remove markdown border

---

src/Diagnostics.DataProviders/DataProviderConfigurations/SupportObserverDataProviderConfiguration.cs
src/Diagnostics.DataProviders/DataProviderContext.cs
src/Diagnostics.DataProviders/DataProviderLogDecorator.cs
src/Diagnostics.DataProviders/DataProviders.cs
src/Diagnostics.DataProviders/DataProviders/Base/SupportObserverDataProviderBase.cs
src/Diagnostics.DataProviders/DataProviders/ISupportObserverDataProvider.cs
src/Diagnostics.DataProviders/DataProviders/MockSupportObserverDataProvider.cs
src/Diagnostics.DataProviders/DataProviders/SupportObserverDataProvider.cs
src/Diagnostics.DataProviders/ISupportBayApiObserverTokenService.cs
src/Diagnostics.DataProviders/IWawsObserverTokenService.cs
src/Diagnostics.DataProviders/KustoTokenService.cs
src/Diagnostics.DataProviders/ObserverTokenService.cs
src/Diagnostics.DataProviders/SupportObserverDataProviderFactory.cs
src/Diagnostics.DataProviders/TokenService/TokenServiceBase.cs
src/Diagnostics.RuntimeHost/Middleware/DiagnosticsRequestMiddleware.cs
src/Diagnostics.RuntimeHost/Startup.cs
src/Diagnostics.RuntimeHost/appsettings.json

- Add logging whenever we're missing swap history data. This will set us up for future alerting.
- Create Observer Token service like Kusto Token Service to account for the possible deadlock issue.

Fix possible deadlock

---

src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/LocalFileSystemWatcher.cs

There was bug that was introduced with the gist feature in the LocalFileSystemWatcher.
`LocalFileSystemWatcher` would throw `NullReferenceExceptions` and thus terminate the loop to load all of the detectors from the file system.
The incorrect `EntityType` was used in the `EntityMetadata` for gists. So the code would assume the gists were detectors and would try to find attributes from the `Run` method but gists don't have run method. So from there it caused some cascading effects that eventually lead to `NullReferenceException` in `LocalFileSystemWatcher`

Fix LocalFileSystemWatcher bug with gist feature

---

src/Diagnostics.CompilerHost/Controllers/CompilerHostController.cs
src/Diagnostics.CompilerHost/Middleware/CompilerRequestMiddleware.cs
src/Diagnostics.DataProviders/ChangeAnalysisClient.cs
src/Diagnostics.DataProviders/ConfigurationFactory.cs
src/Diagnostics.DataProviders/DataProviders/Base/SupportObserverDataProviderBase.cs
src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs
src/Diagnostics.DataProviders/DataProviders/KustoDataProvider.cs
src/Diagnostics.DataProviders/DataProviders/MdmDataProvider.cs
src/Diagnostics.DataProviders/DataProviders/SupportObserverDataProvider.cs
src/Diagnostics.DataProviders/MdmClient/MdmClient.cs
src/Diagnostics.DataProviders/MdmClient/TimeSeriesDefinition.cs
src/Diagnostics.Logger/ApiMetricsLogger.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/Insight.cs
src/Diagnostics.RuntimeHost/Controllers/ApiManagement/ApiManagementController.cs
src/Diagnostics.RuntimeHost/Middleware/DiagnosticsRequestMiddleware.cs

- Log information about Observer requests coming from RuntimeHost
- Code cleanup

Observer Logging

---

src/Diagnostics.DataProviders/DataProviderConfigurations/KustoDataProviderConfiguration.cs
src/Diagnostics.DataProviders/KustoClient.cs
src/Diagnostics.DataProviders/KustoClientFactory.cs

Hardcoded string for Kusto query endpoint will fail in national clouds

Remove hardcoded string for kusto endpoint

---

README.md

Included a few more details in App Service diagnostics based on the open issue in github repo.

adding additional context in readme.md 

---

src/Diagnostics.DataProviders/DataProviders/Base/SupportObserverDataProviderBase.cs
src/Diagnostics.DataProviders/DataProviders/SupportObserverDataProvider.cs

- SQL queries taking over 1 second will be logged for investigation purposes

Add Logging for Slow SQL Queries

---

src/Diagnostics.ModelsAndUtils/Models/Rendering.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/ApplicationInsight.cs

Add Application insight analysis rendering

Add application insight analysis rendering 

---

src/Diagnostics.DataProviders/KustoHeartBeatService/KustoHeartBeatService.cs
src/Diagnostics.RuntimeHost/Services/CompilerHostClient.cs
src/Diagnostics.RuntimeHost/Utilities/Constants.cs
src/Diagnostics.RuntimeHost/appsettings.json

changed some code so Run time host can run independently of compiler host.

Separate Compiler host from Runtime Host

---

src/Diagnostics.ModelsAndUtils/ScriptUtilities/ActionType.cs

Add markdown solution action type

Add markdown solution action type

---

src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs

To get the function level disable information from appsettings, currently we can only get this information by doing this change.
The settings will be like AzureWebJobs.{functionName}.Disabled.
Add the logic to whitelist this too.

White list function disable settings

---

src/Diagnostics.DataProviders/DataProviderConfigurations/GeoMasterDataProviderConfiguration.cs
src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs
src/Diagnostics.DataProviders/GeoCertLoader.cs
src/Diagnostics.DataProviders/GeoMasterCertClient.cs
src/Diagnostics.RuntimeHost/Startup.cs

Load cert from Keyvault on app startup and use that to talk to Geo

Use cert to talk to Geo

---

src/Diagnostics.AIProjects/SearchAPI/Logger.py
src/Diagnostics.AIProjects/SearchAPI/ModelInfo.py
src/Diagnostics.AIProjects/SearchAPI/TokenizerModule.py
src/Diagnostics.AIProjects/SearchAPI/run.pyw
src/Diagnostics.AIProjects/TrainingFactory/DataProcessor.py
src/Diagnostics.AIProjects/TrainingFactory/DetectorsFetcher.py
src/Diagnostics.AIProjects/TrainingFactory/Logger.py
src/Diagnostics.AIProjects/TrainingFactory/ModelTrainer.py
src/Diagnostics.AIProjects/TrainingFactory/SampleUtterancesFetcher.py
src/Diagnostics.AIProjects/TrainingFactory/TextSummarizer.py
src/Diagnostics.AIProjects/TrainingFactory/TokenizerModule.py
src/Diagnostics.AIProjects/TrainingFactory/TrainingConfig.py
src/Diagnostics.AIProjects/TrainingFactory/run.pyw

The changes include
- Code refactoring and adding model configurations to read different kinds of models
- Allowing options to train partially (e.g. only detectors, only utterances, including stackoverflow only, including case titles only)
- Allowing option to breakdown sentences into NGrams
- Allowing option to treat detector utterances as individuals vs group

Changes in search algorithm

---

src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/GitHubWatcher.cs

Aims to Decrease CPU usage after startup by running Source Watcher sequentially when no changes have been detected.

Decrease CPU usage

---

src/Diagnostics.RuntimeHost/Startup.cs

Moved geomaster cert to get initialized before DataSourcesConfigurationService
This change helps make sure the geo master cert has been initialized before it is used.

Moved geomaster cert to get initialized before it is used

---

infrastructure/ArmTemplates/antareskvtemplate.json
infrastructure/ArmTemplates/compilerhost-antareskvparameters.json
infrastructure/ArmTemplates/runtimehost-antareskvparameters.json
infrastructure/README.md

- Add working ARM templates to enable monitoring on RuntimeHost and CompilerHost Web Apps

Add ARM Templates From Geneva Docs

---

src/Diagnostics.CompilerHost/Program.cs
src/Diagnostics.RuntimeHost/Program.cs

This should enable startup failures to be logged to Kusto.

log startup failures to kusto

---

src/Diagnostics.RuntimeHost/Controllers/ProcessHealthController.cs

wait for first source watcher before returning a valid health ping

wait for source watcher on health ping

---

infrastructure/ArmTemplates/FrontDoorDeploy.json

https://docs.microsoft.com/en-us/rest/api/frontdoorservice/frontdoor/frontdoors/get

change front door timeout from 30s to 90s

---

src/Diagnostics.DataProviders/DataProviders/SupportObserverDataProvider.cs

Internal Stamp name works better for observer then external stamp name

---

infrastructure/ArmTemplates/DeployAllTemplate.json
infrastructure/ArmTemplates/antareskvtemplate.json
src/Diagnostics.Logger/ETWProvider/DiagnosticsETWProvider.cs

as WEBSITE_HOSTNAME appears to be flaky I think we need to create an environment variable ourselves.

WEBSITE_HOSTNAME fix

---

infrastructure/ArmTemplates/antareskvtemplate.json

Adding an auto heal rule to prod slots

Auto heal rule

---

data/templates/Detector_Automation.csx
src/Diagnostics.ModelsAndUtils/ScriptUtilities/Utilities.cs
src/Diagnostics.RuntimeHost/Services/ResourceService/SiteService.cs
src/Diagnostics.RuntimeHost/Services/ResourceService/StampService.cs

forward integration

---

src/Diagnostics.CompilerHost/Diagnostics.CompilerHost.csproj
src/Diagnostics.DataProviders/Diagnostics.DataProviders.csproj
src/Diagnostics.Logger/Diagnostics.Logger.csproj

revert compiler host to net core 2.0 to avoid further conflicts with diag role

compiler host revert

---

src/Diagnostics.DataProviders/KustoSDKClient.cs

Fixing in Service Health https://dev.azure.com/app-service-diagnostics-portal/app-service-diagnostics-portal/_workitems/edit/853
- KustoSDKClient was not using failoverclusermapping which was used in KustoClient previously.

Use failover cluster mapping to get the main cluster.

---

src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs

Fix the merge issue in geomaster dataprovider to master2

Fix the merge issue in geomaster dataprovider to master2

---

data/templates/Gist_Automation.csx
data/templates/Gist_BotService.csx
data/templates/Gist_ContainerInstance.csx
data/templates/Gist_ContainerRegistry.csx
data/templates/Gist_MachineLearningServices.csx
data/templates/Gist_OpenShiftManagedClusters.csx
data/templates/Gist_ServiceFabric.csx
data/templates/Gist_SpringCloudService.csx

Add gist template for all resource types that have been onboarded to Applens

Add gist template for partner teams on Applens

---

antares.external.diagnostics.aiprojects.nuspec
antares.external.diagnostics.compilerhost.nuspec
antares.external.diagnostics.runtimehost.nuspec
build.cmd

- Bumped up build versions
- **build.exe** was creating **/build** directory two parent directories up; made this use the current directory, the same directory as **/src**

Create Nuget Packages

---

src/Diagnostics.DataProviders/DataProviders/Base/SupportObserverDataProviderBase.cs
src/Diagnostics.DataProviders/DataProviders/ISupportObserverDataProvider.cs
src/Diagnostics.DataProviders/DataProviders/MockSupportObserverDataProvider.cs
src/Diagnostics.DataProviders/DataProviders/SupportObserverDataProvider.cs
src/Diagnostics.DataProviders/ObserverLogDecorator.cs
src/Diagnostics.RuntimeHost/Utilities/DateTimeHelper.cs
src/Diagnostics.RuntimeHost/Utilities/FileHelper.cs

- Had to close previous PR, Travis CI was hanging

Prevent RuntimeHost From Creating Non-Existent Observer Routes

---

src/Diagnostics.RuntimeHost/Services/SourceWatcher/SourceWatcherService.cs
src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/GitHubWatcher.cs

Remove usage of search service from source watcher

Remove usage of search service from source watcher

---

src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs

White listing a few app settings that help in diagnosing App Insights issues.

Whitelist additional App Settings

---

src/Diagnostics.DataProviders/DataProviders/Base/SupportObserverDataProviderBase.cs
src/Diagnostics.DataProviders/DataProviders/SupportObserverDataProvider.cs
src/Diagnostics.RuntimeHost/Diagnostics.RuntimeHost.csproj

- In load test, reduced connection count from 424 to 10

Use Single HttpClient To Connect To WawsObserver

---

src/Diagnostics.RuntimeHost/Controllers/Site/SiteControllerBase.cs
src/Diagnostics.RuntimeHost/Controllers/Site/SitesController.cs

I verified that no detector is using StackFilter in Definition

User Story 951: Remove Stack filter call from ListDetectors

---

src/Diagnostics.DataProviders/DataProviders/Base/SupportObserverDataProviderBase.cs
src/Diagnostics.DataProviders/DataProviders/ISupportObserverDataProvider.cs
src/Diagnostics.DataProviders/DataProviders/MockSupportObserverDataProvider.cs
src/Diagnostics.DataProviders/DataProviders/SupportObserverDataProvider.cs
src/Diagnostics.DataProviders/ObserverLogDecorator.cs

- Get admin sites using site name or site & stamp

Add GetAdminSites to Public Observer Interface

---

src/Diagnostics.RuntimeHost/Utilities/Constants.cs
src/Diagnostics.RuntimeHost/Utilities/DateTimeHelper.cs

30 seconds leniency in T-15 condition to accomodate the UI to backend request time

30 seconds leniency in T-15 condition to accomodate the UI to backend request time

---

src/Diagnostics.RuntimeHost/Services/ResourceService/SiteService.cs

Changed it to string instead of enum because DiagRole returns string and Diag & Solve UI also consumes as string

Changed return type to string

---

src/Diagnostics.AIProjects/SearchAPI/SearchModule/TextSearchModule.py
src/Diagnostics.AIProjects/SearchAPI/SearchModule/TfIdfSearchModel.py
src/Diagnostics.AIProjects/SearchAPI/SearchModule/WmdSearchModel.py

Patch to retry copy and load files if any of the model files are missing.
Commenting some code and not removing it, as it is essential to keep this code once we make sure that the hosting platform issue is resolved.

Retry on file verification failed

---

src/Diagnostics.ModelsAndUtils/Models/OperationContext.cs
src/Diagnostics.ModelsAndUtils/Models/Rendering.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/DetectorCollection.cs
src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs

* Add QueryParams to OperationContext
* pass additional params to AddDetectorCollection

FI Master to master2

---

src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/DetectorCollection.cs

Previously I added additionalParams as optional param that can causes pre compiled detectors to break. So changed to overloaded method.

Creating overloaded method that accepts additionalParams

---

src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/DetectorCollection.cs

* Creating overloaded method that accepts additionalParams
* Removed as optional param in overloaded method
* Cleaned up

Fixing staging bug 

---

src/Diagnostics.RuntimeHost/Startup.cs

https://stackoverflow.com/questions/47982194/suppressing-console-logging-by-azure-keyvault/48223879#48223879

Disable Console logging for ADAL

---

data/templates/Detector_ApplicationGateway.csx
data/templates/Gist_ApplicationGateway.csx

Adding AppGw detector and gist template

Adding AppGw detector and gist template

---

data/templates/Detector_EventGrid.csx
data/templates/Detector_EventHub.csx
data/templates/Detector_Relay.csx
data/templates/Detector_ServiceBus.csx
data/templates/Gist_EventGrid.csx
data/templates/Gist_EventHub.csx
data/templates/Gist_Relay.csx
data/templates/Gist_ServiceBus.csx

Included templates for Service bus , event grid , event hubs and relay

enable messaging services

---

src/Diagnostics.RuntimeHost/Startup.cs

Remove logging for Public Azure as it causing failures

Remove logging for public azure

---

infrastructure/ArmTemplates/antareskvtemplate.json

- This disables web server logs so that it doesn't take up disk space

Disabling logs to save disk space.

---

src/Diagnostics.Logger/ETWProvider/DiagnosticsETWProvider.cs
src/Diagnostics.Logger/ETWProvider/ETWMessageTemplates.cs
src/Diagnostics.ModelsAndUtils/Diagnostics.ModelsAndUtils.csproj
src/Diagnostics.ModelsAndUtils/Models/OperationContext.cs
src/Diagnostics.ModelsAndUtils/Models/QueryResponse.cs
src/Diagnostics.ModelsAndUtils/Models/RuntimeLogEntry.cs
src/Diagnostics.ModelsAndUtils/ScriptUtilities/ScriptHelper.cs
src/Diagnostics.ModelsAndUtils/ScriptUtilities/Utilities.cs
src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs
src/Diagnostics.RuntimeHost/Startup.cs
src/Diagnostics.RuntimeHost/Utilities/RuntimeLogger.cs

* Add runtime logging feature
* Rename RuntimeEventLogEntry to RuntimeLogEntry
* Remove one comment line, rename RuntimeEventLogEntry.cs
* Rename RuntimeOutput to RuntimeLogOutput
* Remove PreBuild section from csproj

Cherry-pick to master2: Add runtime logging feature (#431)

---

src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs
src/Diagnostics.RuntimeHost/Controllers/Site/SitesController.cs
src/Diagnostics.RuntimeHost/Utilities/DateTimeHelper.cs

Datetime fix for ASC calls

---

src/Diagnostics.AIProjects/SearchAPI/SearchModule/views.py
src/Diagnostics.AIProjects/TrainingAPI/__app__/TrainingModule/TokenizerModule.py

Removing insignificant delimiters pre-training

Removing delimiters before training

---

src/Diagnostics.AIProjects/SearchAPI/SearchModule/Utilities.py

The resource filtering logic had a bug that wouldn't allow search results for any other apps except WebApp and FunctionApp. It has now been fixed.

Fixed bug for api apps in search api

---

infrastructure/ArmTemplates/storage-deploy.json
infrastructure/ArmTemplates/storage-parameters.json
infrastructure/Scripts/storage-postdeployment.ps1

The following arm template creates storage account and a blob container inside it. 
Script can be used to create table since table creation through ARM template is not supported yet.

ARM template for storage and create table

---

src/Diagnostics.Logger/ETWProvider/DiagnosticsETWProvider.cs
src/Diagnostics.RuntimeHost/Utilities/RuntimeLogger.cs

Cherry-picking the missing logs fix from: 06348ee2cdd84cdc4d3c11a34e3eaf71c58534c8
Co-authored-by: Michimune Kohno <mikono@microsoft.com>

Fix missing logs issue in Diag roles (#459)

---

src/Diagnostics.DataProviders/DataProviders/AppInsightsDataProvider.cs
src/Diagnostics.DataProviders/DataProviders/MdmDataProvider.cs
src/Diagnostics.ModelsAndUtils/Models/DataProviderMetadataQuery.cs

* Adding datasource info for AI and MI
* removing extra space
* Changing to ToUnixTimeMilliseconds

Adding DataSources Tab info for AI and MDM (#465)

---

src/Diagnostics.DataProviders/DataProviders/AppInsightsDataProvider.cs
src/Diagnostics.DataProviders/DataProviders/MdmDataProvider.cs
src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs

* Checking for Func instead of Interface
* Adding Params for WebApps dashboard
* Adding seriesResolutionInMinutes
* Fixing AppInsightsDataProvider's NRE
* Checking for metdata.PropertyBag.Count
* Removing check for metada.PropertyBag.Count

Checking for Func instead of Interface (#469)

---

src/Diagnostics.Scripts/EntityInvoker.cs

Cherry-pick commit: 711451ee3c40982060bcae501a186a5f3c56319f
Co-authored-by: Michimune Kohno <mikono@microsoft.com>

Fix runtime error when compiling a gist (#463)

---

infrastructure/ArmTemplates/storage-deploy.json
infrastructure/ArmTemplates/storage-parameters.json

Ran into issue with parameter casing when deploying storage account through devops. Fixed the casing to match parameters file and also stick to ARM's recommendation to use camel case for parameters.

Fixing parameter casing which caused failure in devops pipeline

---

src/Diagnostics.Scripts/EntityInvoker.cs

It is a regression caused by my change 06348ee2cdd84cdc4d3c11a34e3eaf71c58534c8.

Fix gist publishing issue

---

src/Diagnostics.Scripts/EntityInvoker.cs

Cherry-pick PR: 250208a01ab58cd0c1db5508df447ad71adf8528
Co-authored-by: Michimune Kohno <mikono@microsoft.com>

Fix gist publishing issue (#473)

---

data/templates/Detector_SignalRService.csx
data/templates/Gist_SignalRService.csx

Added 2 templates as standard onboarding to AppLens process.

SignalR onboarding process-add template files

---

src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs

Run a detector for every call made from ASC. This can be used to show CSS Wiki links in ASC for every single support topic.

Run a detector for every call made from ASC.

---

src/Diagnostics.RuntimeHost/Services/SupportTopicService/SupportTopicService.cs

Update the Kusto query to pull L2 support topics

Update kusto query to accurately fetch L2 support topic id.

---

src/Diagnostics.ModelsAndUtils/Models/Storage/DiagEntity.cs
src/Diagnostics.RuntimeHost/Services/StorageService/StorageService.cs
src/SourceWatcherFuncApp/DiagSourceWatcher.cs
src/SourceWatcherFuncApp/Services/IStorageService.cs

My plan is to run the function app once so it will mark any detectors not present in github as deleted in storage table. While retrieving the detectors in ListDetectors call, we filter this column.

IsMarkedForDeletion Column for detectors deleted in github

---

infrastructure/ArmTemplates/SearchService/azuredeploy.json
src/Diagnostics.AIProjects/SearchAPI/SearchModule/TextSearchModule.py
src/Diagnostics.AIProjects/SearchAPI/SearchModule/views.py

Sanitize search string before query.
Break long strings into smaller chunks to get better hits across different possible domains.

Heuristic string manipulation for search

---

src/Diagnostics.CompilerHost/Middleware/CompilerRequestMiddleware.cs
src/Diagnostics.Logger/ApiMetricsLogger.cs
src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs
src/Diagnostics.RuntimeHost/Controllers/InternalAPIController.cs
src/Diagnostics.RuntimeHost/Middleware/DiagnosticsRequestMiddleware.cs

Remove duplicates from RequestId

Remove duplicates from RequestId

---

azure-pipelines.yml
src/Diagnostics.RuntimeHost/Services/SupportTopicService/SupportTopicService.cs

Ignore level separating character in support topic string.

Ignore level separating character in support topic string.

---

src/Diagnostics.RuntimeHost/Controllers/LogicApp/LogicAppController.cs

Pass the support topic string as supplied by ASC to lookup support topic id and identify detector mapping for LogicApps.

ASC insight integration for LogicApps

---

src/Diagnostics.DataProviders/KustoSDKClient.cs

Update logic to check if task completed and throw an exception if not

Update logic to check if task completed and throw an exception if not

---

src/Diagnostics.ModelsAndUtils/Attributes/ResourceFilter/Enumerations.cs

Updated StackType to include Sitecore:
public enum StackType
{
None = 0,
AspNet = 1,
NetCore = 2,
Php = 4,
Python = 8,
Node = 16,
Java = 32,
Static = 64,
Sitecore = 128,
Other = 256,
All = 511
}

Updating StackType to include Sitecore

---

src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/StorageWatcher.cs

Setting entity type to be either of the known invoker cache types - Gist or Detector

TryGet InvokerCache based on Partition key

---

src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/StorageWatcher.cs

Moved log statement inside the method to track time taken to download blobs

Logging improvements

---

antares.external.diagnostics.compilerhost.nuspec
antares.external.diagnostics.runtimehost.nuspec

- Update versions
- Match what we have internally

This is the update where we removed System.Interactive.Async.dll

---

src/Diagnostics.RuntimeHost/Services/StorageService/StorageService.cs

This reverts commit ceffefdc01b08d85bd2b651f4bb26109e39e0bea.

Revert "Using geo redundancy to achieve high availability (#553)"

---

data/templates/Detector_SignalRService.csx
data/templates/Gist_SignalRService.csx

Add detector and gist templates for signalR to main branch

Add detector and gist templates for signalR to main branch

---

src/Diagnostics.RuntimeHost/Services/CacheService/DiagEntityTableCacheService.cs
src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/StorageWatcher.cs
src/Diagnostics.RuntimeHost/Services/StorageService/StorageService.cs

- Fixed bug in polling where unhandled exception could cause the loop to break. Wrapped up polling in try catch.
- Retry on exception instead of returning null for table queries.

Retry on exception, fix bug in polling

---

src/SourceWatcherFuncApp/DiagSourceWatcher.cs
src/SourceWatcherFuncApp/Properties/ServiceDependencies/sourcewatcher-dedicated-prod - Web Deploy/profile.arm.json
src/SourceWatcherFuncApp/SourceWatcherFuncApp.csproj

- Use the new Github API to fetch 1000+ directories
- Update metadata column

Use new method to get 1000+ directories, clean up

---

src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/Form.cs

Add tooltip to forms

---

src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs

We added an App Setting called WEBSITE_DAAS_STORAGE_SASURI so this check should hide that

Adding a check for _SASURI in SensitiveAppSettings

---

src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/StorageWatcher.cs

Adding a change that was supposed to be part of this [PR ](https://github.com/Azure/Azure-AppServices-Diagnostics/pull/574)

Load cache with recent detectors only

---

src/Diagnostics.DataProviders/ConfigurationFactory.cs
src/Diagnostics.DataProviders/DataProviderConfigurations/ASCDataProviderConfiguration.cs
src/Diagnostics.DataProviders/DataProviderConfigurations/ChangeAnalysisDataProviderConfiguration.cs
src/Diagnostics.DataProviders/DataProviderConfigurations/DataProviderConfigurationBase.cs
src/Diagnostics.DataProviders/DataProviderConfigurations/KustoDataProviderConfiguration.cs
src/Diagnostics.DataProviders/DataProviderConfigurations/SupportObserverDataProviderConfiguration.cs
src/Diagnostics.DataProviders/Interfaces/IDataProviderConfiguration.cs
src/Diagnostics.RuntimeHost/Startup.cs

Handles validating configuration and fails startup if invalid config is detected

Fail start up in case of invalid configuration

---

azure-pipelines.yml
src/Diagnostics.RuntimeHost/Utilities/RewriteDiagnosticResource.cs

This change will accept call to default / URL with x-ms headers and apply rewrite rule. Existing api/invoke will also be effective.

Interim change to unblock ASC

---

src/Diagnostics.ModelsAndUtils/Models/Rendering.cs
src/Diagnostics.ModelsAndUtils/Models/Response.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/KeystoneComponent.cs

The addition of the Keystone component using res.AddKeystoneComponent() will add a Keystone Insight to the response of the detector.
The detector code to add keystone component looks like:
When a keystone insight is time sensitive, then we add the start date and expiry date like below:
Title and Summary are required attributes to provide in any keystone insight.
If any of them is missing or null, we provide the below exception message.

Keystone component

---

src/Diagnostics.ModelsAndUtils/Utilities/AzureSupportCenterInsightUtilities.cs
src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs
src/Diagnostics.RuntimeHost/Controllers/HostingEnvironment/HostingEnvironmentController.cs
src/Diagnostics.RuntimeHost/Controllers/Site/SitesController.cs

Return an ASC insight indicating that the engineer selected incorrect time instead of a 400 bad request.

Reduce 400 bad request to ASC

---

src/Diagnostics.RuntimeHost/Startup.cs

AKS team is getting 401 from our APIs without reason for failure. Adding some logging to troubleshoot this issue.

Logging AAD failure

---

src/Diagnostics.AIProjects/TrainingAPI/__app__/TrainingModule/HandleRequest.py
src/Diagnostics.AIProjects/TrainingAPI/__app__/TrainingModule/ModelTrainer.py
src/Diagnostics.AIProjects/TrainingAPI/__app__/TrainingModule/StorageAccountHelper.py
src/Diagnostics.AIProjects/TrainingAPI/__app__/TrainingModule/TfIdfTrainer.py
src/Diagnostics.AIProjects/TrainingAPI/__app__/TrainingModule/Utilities.py
src/Diagnostics.AIProjects/TrainingAPI/__app__/TrainingModule/WmdTrainer.py
src/Diagnostics.AIProjects/TrainingAPI/__app__/TriggerTraining/__init__.py
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/KeystoneComponent.cs

Compare with the last trained model to see if any changes have been made that are worth training a new model.

Smart training of Shield detector models

---

src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs
src/Diagnostics.RuntimeHost/Services/SourceWatcher/Watchers/StorageWatcher.cs

Increase interval to 60s and fix existing logic check.

Increase interval, fix existing bug

---

src/Diagnostics.DataProviders/KustoLogDecorator.cs

Have ExecuteClusterQuery call into its respective implementation.

Have ExecuteClusterQuery call into its respective implementation.

---

src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs

Just reusing some logic from this file
https://msazure.visualstudio.com/One/_git/AAPT-Antares-Websites?path=%2Fsrc%2FHosting%2Fcommon%2FMicrosoft.Web.Hosting.Common%2FUtilities%2FCredentialTrap.cs&_a=contents&version=GBdev

Hide secrets in GeoMaster provider

---

src/Diagnostics.ModelsAndUtils/Models/Rendering.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/Tab.cs

This PR adds Tab support for detectors.

Support Tab API

---

src/Diagnostics.ModelsAndUtils/Models/Rendering.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/Section.cs
src/Diagnostics.RuntimeHost/Services/MonitoringService/AuoHealMonitoringService.cs

This is to add a new DataRendering for sectionalize detector 
PR for UI change,
https://github.com/Azure/Azure-AppServices-Diagnostics-Portal/pull/1083

Add section data rendering

---

src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/Section.cs

Update order so title need to pass with a value

Update parameter order for AddSection method

---

src/Diagnostics.DataProviders/KustoHeartBeatService/KustoHeartBeatService.cs

This PR adds some more logging to runtimehost's heart beat tasks to better understand the behavior. It also adds the HeartBeatDelayInSeconds to the log so we can see it via our telemetry.

Add more logging to heartbeat tasks

---

src/Diagnostics.DataProviders/KustoHeartBeatService/KustoHeartBeatService.cs

This PR fixes an issue where multiple kusto heartbeat queries are executed against the same clusters.

Fix duplicated Kusto heartbeat tasks

---

src/Diagnostics.ModelsAndUtils/Models/Rendering.cs

This is the backend change for adding metrics below graph, I set to not display it as default for now

Adding metrics below graph 

---

src/Diagnostics.ModelsAndUtils/Utilities/AzureSupportCenterInsightUtilities.cs

Update Applens link for ASC to point to preview UI.

Update Applens link for ASC to point to preview UI.

---

infrastructure/Scripts/trafficmanager-update.ps1

Adding a script to enable/disable endpoints with Traffic Manager

Added trafficmanager-update script

---

src/Diagnostics.ModelsAndUtils/Utilities/AzureSupportCenterInsightUtilities.cs

Supply a default text when NULL  value is passed while creating ASC insight. This avoids an NRE at ASC.

Supply default text to ASC to avoid NRE

---

data/templates/Detector_MediaService.csx
data/templates/Gist_MediaService.csx

onboarding azure media services to applens

onboarding azure media services to applens

---

src/Diagnostics.ModelsAndUtils/Models/Rendering.cs
src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/Insight.cs

This PR adds the following for improving Linux Log Viewer:
- Insight.IsBackgroundPainted
- TableColumnOption.DefaultSelection

Add Insight.IsBackgroundPainted and TableColumnOption.DefaultSelection

---

src/Diagnostics.ModelsAndUtils/Models/ResponseExtensions/Solution.cs
src/Diagnostics.ModelsAndUtils/ScriptUtilities/SolutionButtonOption.cs

This PR adds a new class named SolutionButtonOptions and a new property of this type into the Solution class, so detector author can customize the UI look of the action button in a solution.

Add SolutionButtonOption

---

src/Diagnostics.ModelsAndUtils/Models/DetectorType.cs

add a new DiagnosticTool detector type for enabling redirecting to diagnostic tool from portal referrer

add a new DiagnosticTool detector type

---

src/Diagnostics.DataProviders/AppInsightsClient.cs
src/Diagnostics.DataProviders/DataProviderContext.cs
src/Diagnostics.DataProviders/DataProviders.cs
src/Diagnostics.DataProviders/DataProviders/AppInsightsDataProvider.cs
src/Diagnostics.ModelsAndUtils/Models/DataTableResponseObject.cs
src/Diagnostics.ModelsAndUtils/ScriptUtilities/Anonymizer.cs
src/Diagnostics.RuntimeHost/Middleware/DiagnosticsRequestMiddleware.cs

Mask any PII data in the data returned by App Insights data provider

Mask PII data from AppInsights data provider

---

src/Diagnostics.DataProviders/DataProviders/GeoMasterDataProvider.cs

<html>
<body>
ID | Title | Iteration Path | State | Tags | Comments | Changed Date
-- | -- | -- | -- | -- | -- | --
1969 | Fix error - The best overloaded method match for 'Diagnostics.DataProviders.CredentialTrapper.Obfuscate(string)' has some invalid arguments) | app-service-diagnostics-portal\2106-1 | New | Service Health | 0 | 7/28/2021, 11:44:48 PM
</body>
</html>

Fix RuntimeBinderException exception calling Obfuscate method

---

data/templates/Detector_WorkerApp.csx
src/Diagnostics.ModelsAndUtils/Attributes/ResourceFilter/Enumerations.cs
src/Diagnostics.ModelsAndUtils/Attributes/ResourceFilter/WorkerAppFilter.cs
src/Diagnostics.ModelsAndUtils/Models/Resource/WorkerApp.cs
src/Diagnostics.RuntimeHost/Controllers/WorkerApp/WorkerAppController.cs
src/Diagnostics.RuntimeHost/Utilities/DiagEntityHelper.cs
src/Diagnostics.RuntimeHost/Utilities/UriElements.cs
src/SourceWatcherFuncApp/Utilities/EntityHelper.cs

WorkerApp = Microsoft.Web/workerApps

Add worker app as resource type in diagnostics backend

---

data/templates/Detector_AzureStackHub.csx
data/templates/Gist_AzureStackHub.csx

Adding support for Azure Stack Hub

Add support for Azure Stack Hub

---

src/Diagnostics.RuntimeHost/Services/StorageService/StorageService.cs

Fixed bug in Listing blobs which is part of `/dependencyCheck`.

Fixed bug in listing blobs

---

data/templates/Detector_ArcAppliance.csx
data/templates/Gist_ArcAppliance.csx

* Added sample detector for Arc Appliance
* Added sample gist for Arc Appliance

Adding support for Arc Appliance

---

data/templates/Detector_devices.csx
data/templates/Gist_devices.csx

Adding templates for Microsoft.HybridNetwork/devices resource for onboarding

Adding templates for Microsoft.HybridNetwork/devices resource

---

src/Diagnostics.Scripts/ApiBlockConfig.json
src/Diagnostics.Scripts/Diagnostics.Scripts.csproj

Update api block config json to restrict potentially dangerous API's

Update api block config json to restrict potentially dangerous API's

---

src/Diagnostics.Scripts/CompilationService/Utilities/APIBlockConfigProvider.cs

Change app setting name to read the config from

Change app setting name to read the config from

---

src/Diagnostics.RuntimeHost/Controllers/DevOpsController.cs
src/Diagnostics.RuntimeHost/Services/DevOpsClient/DevOpsClient.cs
src/Diagnostics.RuntimeHost/Services/DevOpsClient/IRepoClient.cs
src/Diagnostics.RuntimeHost/Services/DevOpsClient/NationalCloudDevOpsClient.cs

when a new detector is created or modified, all the changes will be put into one commit and pushed at the same time

push changes in single commit

---

src/Diagnostics.RuntimeHost/Controllers/DevOpsController.cs
src/Diagnostics.RuntimeHost/Services/DevOpsClient/DevOpsClient.cs

adding delete detector
fixing bad requests return 200
added handling for duplicate detector ids

updates for demo

---

src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs

Adding some logging inside RedactDataResponse to see how much CPU it can burn.
<html>
<body>
ID | Title | Iteration Path | State | Tags | Comments | Changed Date
-- | -- | -- | -- | -- | -- | --
2109 | Look for perf improvements in RedactDataResponse method | app-service-diagnostics-portal\Backlog | Active | Service Health | 0 | 11/17/2021, 7:19:03 PM
</body>
</html>

Log CPU time for RedactDataResponse method

---

src/Diagnostics.RuntimeHost/Extensions/StorageServiceExtensions.cs

This PR fixes a regression introduced by change: 97f800a889adea8116d9d8fce86c6af8cdd383a2

Fix regression

---

src/Diagnostics.Scripts/CompilationService/Utilities/Extensions/DiagnosticExtensions.cs
src/Diagnostics.Scripts/EntityInvoker.cs

Restrict the use of SuppressMessage attribute and #pragma tag. 
Also mask the actual rule id to leave a false trail.

Restrict the use of SuppressMessage attribute and #pragma tag

---

src/Diagnostics.DataProviders/DataProviders/DiagnosticDataProvider.cs
src/Diagnostics.DataProviders/Interfaces/IDiagnosticDataProvider.cs
src/Diagnostics.RuntimeHost/Services/HealthCheckService/HealthCheckService.cs

Change visibility of DataSource config for data providers.

Change visibility of DataSource config for data providers

---

src/LanguageServer/Dockerfile
src/LanguageServer/azure-pipelines.yml
src/LanguageServer/package.json
src/LanguageServer/src/index.html
src/LanguageServer/src/json-server-launcher.js
src/LanguageServer/src/json-server.js
src/LanguageServer/src/server.js
src/LanguageServer/workspace/Solution.csproj
src/LanguageServer/workspace/omnisharp.json

Language server will be hosted on App Service Linux Container. This PR is the code for that server, the dockerfile that builds the image for container, and the devops pipeline that will pick latest dlls after our Runtimehost backend build succeeds to pass onto the language server.

Language server code and deployment

---

src/Diagnostics.DataProviders/DataProviderConfigurations/KustoDataProviderConfiguration.cs
src/Diagnostics.DataProviders/DataProviders/KustoDataProvider.cs
src/Diagnostics.DataProviders/Interfaces/IKustoDataProvider.cs
src/Diagnostics.DataProviders/KustoLogDecorator.cs
src/Diagnostics.DataProviders/KustoSDKClient.cs
src/Diagnostics.RuntimeHost/appsettings.json

release-prod cherry pick: for PR #801, #804 and #808

release-prod cherry pick: for PR #801, #804 and #808

---

src/Diagnostics.ModelsAndUtils/Models/IRequestBodyBase.cs
src/Diagnostics.ModelsAndUtils/Models/Storage/DevopsFileChange.cs
src/Diagnostics.RuntimeHost/Controllers/DevOpsController.cs
src/Diagnostics.RuntimeHost/Utilities/RequestBodyValidator.cs

This PR fixes the DevOps controller routes not receiving a correct request object.

Fix DevOps controller not receiving any JSON body

---

src/Diagnostics.DataProviders/ConfigurationFactory.cs
src/Diagnostics.DataProviders/DataProviderConfigurations/ContainerAppsMdmDataProviderConfiguration.cs
src/Diagnostics.DataProviders/DataProviderConfigurations/GenericMdmDataProviderConfiguration.cs
src/Diagnostics.DataProviders/DataProviderConfigurations/IMdmDataProviderConfiguration.cs
src/Diagnostics.DataProviders/DataProviders.cs
src/Diagnostics.DataProviders/DataProviders/ContainerAppsMdmDataProvider.cs
src/Diagnostics.DataProviders/DataSourcesConfiguration.cs
src/Diagnostics.DataProviders/KeyVaultCertLoader/ContainerAppsMdmCertLoader.cs
src/Diagnostics.DataProviders/MdmClient/MdmClient.cs
src/Diagnostics.DataProviders/MdmClient/MdmClientFactory.cs
src/Diagnostics.DataProviders/MdmDataSource.cs
src/Diagnostics.RuntimeHost/Properties/launchSettings.json
src/Diagnostics.RuntimeHost/Startup.cs
src/Diagnostics.RuntimeHost/appsettings.json

This PR allows detectors to read container apps metrics from MDM.

Enable MDM for container apps

---

data/templates/Detector_RedisCache.csx
data/templates/Gist_RedisCache.csx

Add detector templates for Redis cache

Add detector templates for Redis cache

---

src/Diagnostics.ModelsAndUtils/Attributes/ResourceFilter/ContainerAppFilter.cs
src/Diagnostics.ModelsAndUtils/Models/Resource/ContainerApp.cs
src/Diagnostics.RuntimeHost/Controllers/ContainerApp/ContainerAppController.cs
src/Diagnostics.RuntimeHost/Models/PostBodyModel.cs
src/Diagnostics.RuntimeHost/Utilities/DiagEntityHelper.cs
src/Diagnostics.RuntimeHost/Utilities/UriElements.cs
src/SourceWatcherFuncApp/Utilities/EntityHelper.cs

This PR supports container app's new resource provider type.

Support new RP for container apps

---

src/Diagnostics.RuntimeHost/appsettings.json

add `wawseas|wawseasdiagleader.southeastasia,wawseasfollower|wawseasdiagleader.southeastasia` to QueryShadowingClusterMapping for testing wawseasdiagleader
fix wrong KustoAggClusterNameGroupMappings configs

update kusto configurations

---

src/Diagnostics.ModelsAndUtils/Attributes/ResourceFilter/ContainerAppFilter.cs
src/Diagnostics.ModelsAndUtils/Models/Resource/ContainerApp.cs
src/Diagnostics.RuntimeHost/Controllers/ContainerApp/ContainerAppController.cs
src/Diagnostics.RuntimeHost/Models/PostBodyModel.cs
src/Diagnostics.RuntimeHost/Utilities/DiagEntityHelper.cs
src/Diagnostics.RuntimeHost/Utilities/UriElements.cs
src/SourceWatcherFuncApp/Utilities/EntityHelper.cs

This reverts commit 1552d573a48e432fd92c18db59154981e06edfbd.

Revert "Support new RP for container apps (#827)"

---

src/Diagnostics.DataProviders/DataProviders/KustoDataProvider.cs
src/Diagnostics.DataProviders/KustoSDKClient.cs
src/Diagnostics.RuntimeHost/appsettings.json

- remove easdiagleader from shadowing list
- check maxOfMinExtentsCreationTime before shadowing to diagleader and sending query to aggdiagleader

update kusto settings

---

src/Diagnostics.RuntimeHost/Controllers/DiagnosticControllerBase.cs

Fix NRE in GetInsights and add additional logging to further investigate the issue.

Fix NRE in GetInsights

---

src/Diagnostics.RuntimeHost/Utilities/DiagEntityHelper.cs

This PR adds a missing resource filter for the new container app resource type.

Add missing resource filter for new container app resource type

---

src/Diagnostics.RuntimeHost/appsettings.json

Update the value of AAD Authority for ASC to lowercase.

Update the value of AAD Authority for ASC to lowercase.
